# -*- coding: utf-8 -*-
"""Classification (Final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196Sx3TM86vchJj1Ak_pAsPnd9x5knWI5

# **Classification**

**Prerequisites:**
"""

# timm 0.6.13 — required for efficientnet_lite0
!pip install timm==0.6.13 --quiet
# pretrainedmodels — used for NASNet-Mobile (removed from timm ≥ 0.9.x)
!pip install pretrainedmodels --quiet

from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive')

import gc
import os
import ssl
import math
import copy
import urllib.request
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import torchvision.models as tv_models

import timm
import pretrainedmodels
from tqdm import tqdm
import cv2

gc.collect()
torch.cuda.empty_cache()
print('Imports OK')
print('torch:', torch.__version__)
print('timm :', timm.__version__)

"""**Configuration:**"""

PROJECT_ROOT = "/content/drive/MyDrive/thesis"

TRAIN_CSV  = os.path.join(PROJECT_ROOT, "data/metadata/train.csv")
TEST_CSV   = os.path.join(PROJECT_ROOT, "data/metadata/test.csv")

MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
META_DIR   = os.path.join(PROJECT_ROOT, "data/metadata")

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(META_DIR,   exist_ok=True)

IMG_SIZE      = 224
BATCH_SIZE    = 32
NUM_CLASSES   = 4
EPOCHS        = 50
LR            = 1e-4
WARMUP_EPOCHS = 3
PATIENCE      = 15
RANDOM_STATE  = 42
NUM_WORKERS   = 2

MIXUP_ALPHA      = 0.2
SWA_START_EPOCH  = 30

CLASS_NAMES = {
    0: "Bacterial Leaf Blight",
    1: "Brown Spot",
    2: "Nutrient Deficiency",
    3: "Healthy",
}

NUTRIENT_DEF_IDX = 2

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print('DEVICE      :', DEVICE)
print('IMG_SIZE    :', IMG_SIZE)
print('BATCH_SIZE  :', BATCH_SIZE)
print('NUM_CLASSES :', NUM_CLASSES)
print('EPOCHS max  :', EPOCHS)
print('PATIENCE    :', PATIENCE)
print('MIXUP_ALPHA :', MIXUP_ALPHA)
print('SWA_START   :', SWA_START_EPOCH)

"""**Loss Functions:**"""

class FocalLoss(nn.Module):
    def __init__(self, gamma=1.0, label_smoothing=0.05,
                 num_classes=4, class_weights=None):
        super().__init__()
        self.gamma           = gamma
        self.label_smoothing = label_smoothing
        self.num_classes     = num_classes
        self.register_buffer(
            'class_weights',
            class_weights if class_weights is not None
            else torch.ones(num_classes)
        )

    def forward(self, logits, targets):
        with torch.no_grad():
            soft = torch.full_like(
                logits, self.label_smoothing / (self.num_classes - 1))
            soft.scatter_(1, targets.unsqueeze(1), 1.0 - self.label_smoothing)

        log_probs = F.log_softmax(logits, dim=1)
        probs     = log_probs.exp()
        p_t       = (probs * soft).sum(dim=1)
        weight    = (1.0 - p_t) ** self.gamma

        # FIX: move class_weights to same device as targets before indexing
        sample_weights = self.class_weights.to(targets.device)[targets]

        loss = -(soft * log_probs).sum(dim=1)
        return (weight * sample_weights * loss).mean()

print("✅ FocalLoss defined")

"""**MixUp Utilities:**"""

def mixup_batch(images, labels, alpha=0.2, num_classes=NUM_CLASSES):
    lam   = np.random.beta(alpha, alpha) if alpha > 0 else 1.0
    idx   = torch.randperm(images.size(0), device=images.device)
    mixed = lam * images + (1 - lam) * images[idx]
    return mixed, labels, labels[idx], lam

def mixup_criterion(criterion, logits, y_a, y_b, lam):
    return lam * criterion(logits, y_a) + (1 - lam) * criterion(logits, y_b)

print("✅ MixUp utilities defined")

"""**Load CSV:**"""

LEGACY_ROOTS = [
    "/content/drive/MyDrive/Thesis Model",
    "/content/drive/MyDrive/Thesis_Model",
]
NEW_ROOT = "/content/drive/MyDrive/thesis"

def repair_paths(df):
    df = df.copy()
    for old in LEGACY_ROOTS:
        df["image_path"] = df["image_path"].str.replace(old, NEW_ROOT, regex=False)
        df["mask_path"]  = df["mask_path"].str.replace(old, NEW_ROOT, regex=False)
    return df

train_full_df = repair_paths(pd.read_csv(TRAIN_CSV))
test_df       = repair_paths(pd.read_csv(TEST_CSV))

# class_id in CSV is 1-indexed → shift to 0-indexed label
train_full_df["label"] = train_full_df["class_id"] - 1
test_df["label"]       = test_df["class_id"] - 1

print(f"Train full: {len(train_full_df)}  Test: {len(test_df)}")
print("\nClass distribution:")
print(train_full_df["class_name"].value_counts())

"""**Train / Val Split:**"""

from sklearn.model_selection import train_test_split
train_df, val_df = train_test_split(
    train_full_df, test_size=0.15,
    stratify=train_full_df["label"], random_state=RANDOM_STATE
)
print(f"Train: {len(train_df)}  Val: {len(val_df)}  Test: {len(test_df)}")

"""**CSV Integrity Validation:**"""

def drop_unreadable(df, split_name):
    bad = [p for p in df["image_path"] if cv2.imread(p) is None]
    if bad:
        print(f"[{split_name}] Dropping {len(bad)} unreadable image(s):")
        for p in bad[:5]:
            print(f"  ✗ {p}")
        if len(bad) > 5:
            print(f"  ... and {len(bad)-5} more")
    else:
        print(f"[{split_name}] All images readable ✅")
    return df[~df["image_path"].isin(bad)].reset_index(drop=True)

train_df = drop_unreadable(train_df, "TRAIN")
val_df   = drop_unreadable(val_df,   "VAL")
test_df  = drop_unreadable(test_df,  "TEST")
print(f"\nAfter filtering — Train: {len(train_df)}  "
      f"Val: {len(val_df)}  Test: {len(test_df)}")

"""**Augmentation Transforms:**"""

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_transform = T.Compose([
    T.ToPILImage(),
    T.RandomResizedCrop(IMG_SIZE, scale=(0.65, 1.0), ratio=(0.75, 1.33)),
    T.RandomHorizontalFlip(p=0.5),
    T.RandomVerticalFlip(p=0.3),
    T.RandomRotation(degrees=35),
    # ElasticTransform REMOVED — scrambled lesion texture features
    # RandomPerspective REMOVED — same reason
    T.ColorJitter(brightness=0.35, contrast=0.35, saturation=0.35, hue=0.12),
    T.RandomGrayscale(p=0.05),
    T.ToTensor(),
    T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    T.RandomErasing(p=0.25, scale=(0.02, 0.12)),
])

val_transform = T.Compose([
    T.ToPILImage(),
    T.Resize((IMG_SIZE, IMG_SIZE)),
    T.ToTensor(),
    T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])

print(f"Train transforms : {len(train_transform.transforms)} stages")
print(f"Val   transforms : {len(val_transform.transforms)} stages")

"""**Dataset:**"""

class ClassificationDataset(Dataset):

    def __init__(self, df, transform=None, use_mixup=False):
        self.df        = df.reset_index(drop=True)
        self.transform = transform
        self.use_mixup = use_mixup
        self._warned   = set()

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        label = int(row["label"])

        image = cv2.imread(row["image_path"])
        if image is None:
            if row["image_path"] not in self._warned:
                print(f"\n⚠️  Unreadable at runtime: {row['image_path']}")
                self._warned.add(row["image_path"])
            return torch.zeros(3, IMG_SIZE, IMG_SIZE, dtype=torch.float32), -1

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        if self.transform:
            image = self.transform(image)
        return image, label

print("✅ ClassificationDataset defined")

"""**Dataloaders:**"""

def make_loaders(batch_size=BATCH_SIZE, weighted_oversample=True):
    train_ds = ClassificationDataset(train_df, transform=train_transform)
    val_ds   = ClassificationDataset(val_df,   transform=val_transform)
    test_ds  = ClassificationDataset(test_df,  transform=val_transform)

    kw = dict(num_workers=NUM_WORKERS, pin_memory=True)

    if weighted_oversample:
        labels        = train_df["label"].values
        class_counts  = np.bincount(labels, minlength=NUM_CLASSES)
        class_weights = 1.0 / np.maximum(class_counts, 1)
        sample_weights = class_weights[labels]
        sampler = torch.utils.data.WeightedRandomSampler(
            weights=torch.from_numpy(sample_weights).float(),
            num_samples=len(train_ds),
            replacement=True,
        )
        train_loader = DataLoader(train_ds, batch_size=batch_size,
                                  sampler=sampler, **kw)
        print("Train loader : WeightedRandomSampler (oversampling minority classes)")
        for c, cnt in enumerate(class_counts):
            print(f"  class {c} ({CLASS_NAMES[c]:<25}): {cnt} samples")
    else:
        train_loader = DataLoader(train_ds, batch_size=batch_size,
                                  shuffle=True, **kw)

    val_loader  = DataLoader(val_ds,  batch_size=batch_size, shuffle=False, **kw)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, **kw)

    print(f"Train batches : {len(train_loader)}")
    print(f"Val batches   : {len(val_loader)}")
    print(f"Test batches  : {len(test_loader)}")
    return train_loader, val_loader, test_loader

print("✅ make_loaders() ready")

"""**Model:**"""

def _param_groups(model, head_params, lr):
    head_ids    = {id(p) for p in head_params}
    body_params = [p for p in model.parameters() if id(p) not in head_ids]
    return [
        {"params": body_params, "lr": lr * 0.05},
        {"params": head_params, "lr": lr},
    ]


def build_mobilenetv3(num_classes=NUM_CLASSES, lr=LR):
    model = tv_models.mobilenet_v3_large(
        weights=tv_models.MobileNet_V3_Large_Weights.IMAGENET1K_V2)
    in_features = model.classifier[-1].in_features
    model.classifier[-1] = nn.Linear(in_features, num_classes)
    model = model.to(DEVICE)
    head_params = list(model.classifier.parameters())
    optimizer   = torch.optim.AdamW(
        _param_groups(model, head_params, lr), weight_decay=1e-4)
    total, trainable = count_params(model)
    print(f"MobileNetV3-Large  |  {total:,} total params  |  {trainable:,} trainable")
    return model, optimizer


def build_nasnet_mobile(num_classes=NUM_CLASSES, lr=LR):
    """
    NASNet-Mobile via pretrainedmodels.
    Weights are downloaded once from the Wayback Machine archive and cached
    at ~/.cache/torch/hub/checkpoints to survive Colab session restarts.
    Early conv layers are frozen to prevent catastrophic forgetting on this
    small dataset; the rest uses differential LR fine-tuning.
    """
    import subprocess

    ckpt_dir  = os.path.expanduser("~/.cache/torch/hub/checkpoints")
    ckpt_file = os.path.join(ckpt_dir, "nasnetamobile-7e03cead.pth")

    os.makedirs(ckpt_dir, exist_ok=True)

    if not os.path.exists(ckpt_file):
        url = (
            "https://web.archive.org/web/2024/http://data.lip6.fr/cadene/pretrainedmodels/"
            "nasnetamobile-7e03cead.pth"
        )
        print("Downloading NASNet-Mobile weights...")
        subprocess.run(
            ["wget", "--no-check-certificate", "-q", "-O", ckpt_file, url],
            check=True
        )
        print("✅ Download complete.")
    else:
        print("✅ NASNet-Mobile weights already cached.")

    model = pretrainedmodels.__dict__["nasnetamobile"](
        num_classes=1000, pretrained="imagenet")

    in_features = model.last_linear.in_features
    model.last_linear = nn.Sequential(
        nn.Dropout(0.2),
        nn.Linear(in_features, num_classes)
    )

    # Freeze early conv layers — NASNet overfits badly if fully unfrozen immediately
    freeze_prefixes = ["conv0"]
    for name, param in model.named_parameters():
        if any(name.startswith(p) for p in freeze_prefixes):
            param.requires_grad = False

    model = model.to(DEVICE)

    head_params = list(model.last_linear.parameters())
    head_ids    = {id(p) for p in head_params}
    body_params = [p for p in model.parameters()
                   if p.requires_grad and id(p) not in head_ids]

    optimizer = torch.optim.AdamW([
        {"params": body_params, "lr": lr * 0.05, "weight_decay": 3e-4},
        {"params": head_params, "lr": lr,         "weight_decay": 5e-4},
    ])

    total, trainable = count_params(model)
    print(f"NASNet-Mobile  |  {total:,} total params  |  {trainable:,} trainable")
    return model, optimizer


def build_efficientnet_lite(num_classes=NUM_CLASSES, lr=LR,
                             dropout_rate=0.2, freeze_body=False):
    """
    dropout_rate default lowered to 0.2 (was 0.3).
    MixUp already provides strong regularisation; stacking 0.3 dropout
    on top was over-regularising on this small dataset.
    """
    model = timm.create_model("efficientnet_lite0", pretrained=True,
                               num_classes=num_classes, drop_rate=dropout_rate)
    model = model.to(DEVICE)

    if freeze_body:
        for param in model.parameters():
            param.requires_grad = False
        for param in model.classifier.parameters():
            param.requires_grad = True
        head_params = list(model.classifier.parameters())
        optimizer   = torch.optim.AdamW(head_params, lr=lr, weight_decay=5e-4)
    else:
        head_params = list(model.classifier.parameters())
        optimizer   = torch.optim.AdamW(
            _param_groups(model, head_params, lr), weight_decay=5e-4)

    total, trainable = count_params(model)
    frozen = "(body frozen)" if freeze_body else ""
    print(f"EfficientNet-Lite0  |  {total:,} total  |  {trainable:,} trainable {frozen}")
    return model, optimizer


def count_params(model):
    total     = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return total, trainable


def cosine_with_warmup_scheduler(optimizer, warmup_epochs, total_epochs,
                                  min_lr_ratio=1e-3):
    def fn(epoch):
        if epoch < warmup_epochs:
            return (epoch + 1) / warmup_epochs
        progress = (epoch - warmup_epochs) / max(1, total_epochs - warmup_epochs)
        cosine   = 0.5 * (1.0 + math.cos(math.pi * progress))
        return max(cosine * (1.0 - min_lr_ratio) + min_lr_ratio, min_lr_ratio)
    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=fn)

print("✅ Model factory ready")

"""**Metrics:**"""

def compute_metrics(all_preds, all_labels, print_cm=False):
    preds  = np.array(all_preds)
    labels = np.array(all_labels)

    mask   = labels != -1
    preds  = preds[mask]
    labels = labels[mask]

    if len(labels) == 0:
        return {"accuracy": 0, "precision": 0, "recall": 0, "f1": 0,
                "fpr_nutrient_def": 0, "per_class_f1": {},
                "confusion_matrix": np.zeros((4, 4))}

    acc    = accuracy_score(labels, preds)
    prec   = precision_score(labels, preds, average="weighted", zero_division=0)
    rec    = recall_score(labels,    preds, average="weighted", zero_division=0)
    f1     = f1_score(labels,        preds, average="weighted", zero_division=0)
    f1_per = f1_score(labels,        preds, average=None,       zero_division=0)

    cm     = confusion_matrix(labels, preds, labels=list(range(NUM_CLASSES)))
    nd_idx = NUTRIENT_DEF_IDX
    fp_nd  = cm[:, nd_idx].sum() - cm[nd_idx, nd_idx]
    tn_nd  = (cm.sum() - cm[nd_idx, :].sum()
              - cm[:, nd_idx].sum() + cm[nd_idx, nd_idx])
    fpr_nd = float(fp_nd) / float(fp_nd + tn_nd) if (fp_nd + tn_nd) > 0 else 0.0

    if print_cm:
        print("\nConfusion Matrix:")
        print(pd.DataFrame(
            cm,
            index=[f"True: {CLASS_NAMES[i]}"   for i in range(NUM_CLASSES)],
            columns=[f"Pred: {CLASS_NAMES[i]}" for i in range(NUM_CLASSES)]
        ).to_string())

    return {
        "accuracy":         acc,
        "precision":        prec,
        "recall":           rec,
        "f1":               f1,
        "fpr_nutrient_def": fpr_nd,
        "per_class_f1": {CLASS_NAMES[i]: round(float(v), 4)
                         for i, v in enumerate(f1_per)},
        "confusion_matrix": cm,
        "all_preds":        preds,
        "all_labels":       labels,
    }

print("✅ compute_metrics() ready")

"""**Training Loop:**"""

def train_model(model, optimizer, scheduler, train_loader, val_loader,
                model_name, epochs=EPOCHS, patience=PATIENCE,
                save_dir=MODELS_DIR, use_focal_loss=True,
                gamma=2.0, label_smoothing=0.05, use_mixup=True,
                mixup_alpha=0.2, swa_start=None, class_weights=None):

    if use_focal_loss:
        criterion = FocalLoss(
            gamma=gamma,
            label_smoothing=label_smoothing,
            num_classes=NUM_CLASSES,
            class_weights=class_weights,
        )
        cw_str = ("custom" if class_weights is not None else "uniform")
        print(f"Using Focal Loss (gamma={gamma}, smoothing={label_smoothing}, "
              f"class_weights={cw_str})")
    else:
        criterion = nn.CrossEntropyLoss(label_smoothing=label_smoothing)
        print(f"Using CrossEntropyLoss (smoothing={label_smoothing})")

    # FIX: consistent val criterion — plain CE, always, regardless of use_mixup
    val_criterion = nn.CrossEntropyLoss(label_smoothing=label_smoothing)

    scaler    = torch.amp.GradScaler('cuda')
    save_path = os.path.join(save_dir, f"best_{model_name}.pth")

    if swa_start is not None and swa_start < epochs:
        from torch.optim.swa_utils import AveragedModel, update_bn
        swa_model = AveragedModel(model)
        print(f"SWA enabled — starting at epoch {swa_start + 1}")
    else:
        swa_model = None
        swa_start = epochs + 1

    best_f1          = 0.0
    patience_counter = 0

    history = {
        "train_loss": [], "train_acc": [],
        "val_loss":   [], "val_acc":   [],
        "val_f1":     [], "val_fpr_nd": [], "lr": [],
    }

    print(f"\n{'='*60}")
    print(f"  Training: {model_name}")
    print(f"{'='*60}")

    for epoch in range(epochs):

        # ── TRAIN ───────────────────────────────────────────
        model.train()
        t_losses, t_preds, t_labels = [], [], []

        for images, labels in tqdm(train_loader,
                                   desc=f"Train {epoch+1}/{epochs}",
                                   leave=False):
            images = images.to(DEVICE)
            labels = labels.to(DEVICE)
            valid  = labels != -1
            if valid.sum() == 0:
                continue
            images = images[valid]
            labels = labels[valid]

            optimizer.zero_grad(set_to_none=True)

            with torch.amp.autocast("cuda"):
                if use_mixup and epoch >= 2:
                    mixed_images, y_a, y_b, lam = mixup_batch(
                        images, labels, alpha=mixup_alpha)
                    outputs = model(mixed_images)
                    loss    = mixup_criterion(criterion, outputs, y_a, y_b, lam)
                    preds   = torch.argmax(outputs, 1).cpu().numpy()
                    true_labels = y_a if lam >= 0.5 else y_b
                    t_preds.extend(preds)
                    t_labels.extend(true_labels.cpu().numpy())
                else:
                    outputs = model(images)
                    loss    = criterion(outputs, labels)
                    t_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
                    t_labels.extend(labels.cpu().numpy())

                t_losses.append(loss.item())

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()

        scheduler.step()
        current_lr = optimizer.param_groups[-1]["lr"]

        train_loss = np.mean(t_losses)
        train_acc  = accuracy_score(t_labels, t_preds)

        # ── VALIDATE ────────────────────────────────────────
        model.eval()
        v_losses, v_preds, v_labels = [], [], []

        with torch.no_grad():
            for images, labels in val_loader:
                images = images.to(DEVICE)
                labels = labels.to(DEVICE)
                valid  = labels != -1
                if valid.sum() == 0:
                    continue
                images = images[valid]
                labels = labels[valid]
                with torch.amp.autocast("cuda"):
                    outputs = model(images)
                    loss = val_criterion(outputs, labels)
                v_losses.append(loss.item())
                v_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
                v_labels.extend(labels.cpu().numpy())

        val_loss    = np.mean(v_losses)
        val_metrics = compute_metrics(v_preds, v_labels)
        val_acc     = val_metrics["accuracy"]
        val_f1      = val_metrics["f1"]
        val_fpr_nd  = val_metrics["fpr_nutrient_def"]

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)
        history["val_f1"].append(val_f1)
        history["val_fpr_nd"].append(val_fpr_nd)
        history["lr"].append(current_lr)

        if swa_model is not None and epoch >= swa_start:
            swa_model.update_parameters(model)

        print(f"  Ep {epoch+1:>3}/{epochs}  LR={current_lr:.2e}"
              f"  Loss={train_loss:.4f}/{val_loss:.4f}"
              f"  Acc={train_acc:.4f}/{val_acc:.4f}"
              f"  F1={val_f1:.4f}"
              f"  FPR_ND={val_fpr_nd:.4f}", end="")

        if val_f1 > best_f1:
            best_f1          = val_f1
            patience_counter = 0
            torch.save({
                "epoch":                epoch + 1,
                "model_state_dict":     model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "best_f1":              best_f1,
            }, save_path)
            print(f"  💾 best={best_f1:.4f}")
        else:
            patience_counter += 1
            print(f"  ({patience_counter}/{patience})")
            if patience_counter >= patience:
                print(f"\n  ⏹  Early stopping at epoch {epoch+1}")
                break

    if swa_model is not None and epoch >= swa_start:
        print("\n  📊 Updating SWA batch normalization statistics...")
        update_bn(train_loader, swa_model, device=DEVICE)
        model = swa_model
        print("  ✅ SWA model ready for evaluation")

    print(f"\n✅ {model_name} done — Best Val F1: {best_f1:.4f}")
    print(f"   Checkpoint: {save_path}")
    return model, history, save_path, best_f1

print("✅ train_model() ready")

"""**Evaluation:**"""

def predict_with_thresholds(model, loader, thresholds=None, device=DEVICE):
    if thresholds is None:
        thresholds = [0.25] * NUM_CLASSES
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in tqdm(loader, desc="Threshold prediction", leave=False):
            images = images.to(device)
            labels = labels.numpy()
            valid  = labels != -1
            if valid.sum() == 0:
                continue
            images = images[valid]
            probs  = torch.softmax(model(images), dim=1).cpu().numpy()
            scaled = probs / np.array(thresholds)
            preds  = scaled.argmax(axis=1)
            all_preds.extend(preds)
            all_labels.extend(labels[valid])
    return all_preds, all_labels


def evaluate_model(model, test_loader, save_path, model_name, tune_threshold=False):
    checkpoint = torch.load(save_path, map_location=DEVICE)
    # FIX: unwrap SWA AveragedModel if present
    target = model.module if hasattr(model, 'module') else model
    target.load_state_dict(checkpoint["model_state_dict"])
    print(f"Loaded checkpoint  epoch={checkpoint['epoch']}  "
          f"val F1={checkpoint['best_f1']:.4f}")

    if tune_threshold and model_name == "EfficientNet-Lite0":
        print("\n  🔧 Tuning threshold for Nutrient Deficiency...")
        from torch.utils.data import Subset
        val_ds = ClassificationDataset(val_df, transform=val_transform)
        val_subset = Subset(
            val_ds,
            np.random.choice(len(val_ds), min(200, len(val_ds)), replace=False)
        )
        val_tune_loader = DataLoader(val_subset, batch_size=BATCH_SIZE, shuffle=False)

        best_f1_tune = 0
        best_thresh  = 0.25
        for nd_thresh in [0.25, 0.22, 0.20, 0.18, 0.15, 0.12, 0.10]:
            thresholds = [0.25, 0.25, nd_thresh, 0.25]
            preds, labs = predict_with_thresholds(model, val_tune_loader, thresholds)
            m    = compute_metrics(preds, labs)
            nd_f1 = m["per_class_f1"].get("Nutrient Deficiency", 0)
            print(f"    ND thresh={nd_thresh:.3f} → "
                  f"ND F1={nd_f1:.4f}, overall F1={m['f1']:.4f}")
            if m['f1'] > best_f1_tune:
                best_f1_tune = m['f1']
                best_thresh  = nd_thresh

        print(f"  ✅ Best ND threshold: {best_thresh:.3f} (F1={best_f1_tune:.4f})")
        thresholds = [0.25, 0.25, best_thresh, 0.25]
        all_preds, all_labels = predict_with_thresholds(
            model, test_loader, thresholds)
    else:
        model.eval()
        all_preds, all_labels = [], []
        with torch.no_grad():
            for images, labels in tqdm(test_loader,
                                       desc=f"Testing {model_name}", leave=False):
                images = images.to(DEVICE)
                labels = labels.numpy()
                valid  = labels != -1
                if valid.sum() == 0:
                    continue
                with torch.amp.autocast("cuda"):
                    outputs = model(images[valid])
                all_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
                all_labels.extend(labels[valid])

    metrics = compute_metrics(all_preds, all_labels, print_cm=False)

    print(f"\n── {model_name} — TEST RESULTS ──────────────────────────")
    print(f"  Accuracy                      : {metrics['accuracy']:.4f}")
    print(f"  Precision (weighted)          : {metrics['precision']:.4f}")
    print(f"  Recall    (weighted)          : {metrics['recall']:.4f}")
    print(f"  F1        (weighted)          : {metrics['f1']:.4f}")
    print(f"  FPR — Nutrient Deficiency     : {metrics['fpr_nutrient_def']:.4f}")

    print("\nPer-class F1:")
    for cls, f1v in metrics["per_class_f1"].items():
        status = "✅" if f1v >= 0.90 else "⚠️ "
        print(f"  {status} {cls}: {f1v:.4f}")

    print("\nClassification Report:")
    print(classification_report(
        metrics["all_labels"], metrics["all_preds"],
        labels=list(range(NUM_CLASSES)),
        target_names=list(CLASS_NAMES.values()), digits=4,
        zero_division=0))

    fig, ax = plt.subplots(figsize=(7, 6))
    short_names = [n.split()[0] for n in CLASS_NAMES.values()]
    sns.heatmap(metrics["confusion_matrix"], annot=True, fmt="d",
                cmap="Blues", ax=ax,
                xticklabels=short_names, yticklabels=short_names, cbar=True)
    ax.set_title(f"{model_name} — Confusion Matrix\n"
                 f"F1={metrics['f1']:.4f}  Acc={metrics['accuracy']:.4f}"
                 f"  FPR_ND={metrics['fpr_nutrient_def']:.4f}", fontsize=11)
    ax.set_ylabel("True"); ax.set_xlabel("Predicted")
    plt.tight_layout()
    cm_fname = os.path.join(
        META_DIR,
        f"confusion_matrix_{model_name.lower().replace(' ', '_')}.png")
    plt.savefig(cm_fname, dpi=120)
    plt.show()
    print(f"✅ Saved {cm_fname}")

    return metrics

print("✅ evaluate_model() ready")

"""**Training Curves:**"""

def plot_history(history, model_name, meta_dir=META_DIR):
    n = len(history["train_loss"])
    x = range(1, n + 1)

    fig, axes = plt.subplots(1, 4, figsize=(20, 4))
    fig.suptitle(f"Training History — {model_name}", fontsize=13)

    axes[0].plot(x, history["train_loss"], label="Train", color="steelblue")
    axes[0].plot(x, history["val_loss"],   label="Val",   color="darkorange")
    axes[0].set_title("Loss"); axes[0].set_xlabel("Epoch")
    axes[0].legend(); axes[0].grid(True)

    axes[1].plot(x, history["train_acc"], label="Train Acc", color="steelblue")
    axes[1].plot(x, history["val_acc"],   label="Val Acc",   color="darkorange")
    axes[1].plot(x, history["val_f1"],    label="Val F1",    color="green",
                 linestyle="--")
    axes[1].axhline(0.90, color="red", linestyle=":", alpha=0.6, label="Target 0.90")
    axes[1].set_title("Accuracy / F1"); axes[1].set_xlabel("Epoch")
    axes[1].legend(fontsize=8); axes[1].grid(True)

    axes[2].plot(x, history["val_fpr_nd"], color="crimson",
                 label="FPR — Nutrient Def")
    axes[2].set_title("Val FPR — Nutrient Deficiency")
    axes[2].set_xlabel("Epoch"); axes[2].set_ylim(0, 1)
    axes[2].legend(fontsize=8); axes[2].grid(True)

    axes[3].plot(x, history["lr"], color="purple")
    axes[3].set_title("Learning Rate (head)")
    axes[3].set_xlabel("Epoch")
    axes[3].set_yscale("log"); axes[3].grid(True)

    plt.tight_layout()
    fname = os.path.join(
        meta_dir,
        f"training_curves_{model_name.lower().replace(' ', '_')}.png")
    plt.savefig(fname, dpi=120)
    plt.show()
    print(f"✅ Saved {fname}")

print("✅ plot_history() ready")

"""**MobileNetV3-Large:**"""

gc.collect(); torch.cuda.empty_cache()
train_loader, val_loader, test_loader = make_loaders(weighted_oversample=True)

mobilenet_model, mobilenet_opt = build_mobilenetv3()
mobilenet_sched = cosine_with_warmup_scheduler(
    mobilenet_opt, warmup_epochs=WARMUP_EPOCHS, total_epochs=EPOCHS)

mobilenet_model, mobilenet_history, mobilenet_ckpt, mobilenet_best_f1 = train_model(
    model           = mobilenet_model,
    optimizer       = mobilenet_opt,
    scheduler       = mobilenet_sched,
    train_loader    = train_loader,
    val_loader      = val_loader,
    model_name      = "mobilenetv3_large",
    epochs          = EPOCHS,
    use_focal_loss  = True,
    gamma           = 2.0,
    label_smoothing = 0.05,
    use_mixup       = True,
    mixup_alpha     = 0.2,
    swa_start       = SWA_START_EPOCH,
    class_weights   = None,
)

plot_history(mobilenet_history, 'MobileNetV3-Large')
mobilenet_metrics = evaluate_model(
    mobilenet_model, test_loader, mobilenet_ckpt,
    "MobileNetV3-Large", tune_threshold=False)

"""**NASNet-Mobile:**"""

gc.collect(); torch.cuda.empty_cache()
train_loader, val_loader, test_loader = make_loaders(weighted_oversample=True)

nasnet_model, nasnet_opt = build_nasnet_mobile()
nasnet_sched = cosine_with_warmup_scheduler(
    nasnet_opt, warmup_epochs=WARMUP_EPOCHS, total_epochs=EPOCHS)

nasnet_model, nasnet_history, nasnet_ckpt, nasnet_best_f1 = train_model(
    model           = nasnet_model,
    optimizer       = nasnet_opt,
    scheduler       = nasnet_sched,
    train_loader    = train_loader,
    val_loader      = val_loader,
    model_name      = "nasnetamobile",
    epochs          = EPOCHS,
    use_focal_loss  = True,
    gamma           = 2.0,
    label_smoothing = 0.01,
    use_mixup       = True,
    mixup_alpha     = 0.1,
    swa_start       = 30,
    class_weights   = torch.tensor([1.2, 1.0, 1.8, 1.0], device=DEVICE)
)

plot_history(nasnet_history, 'NASNet-Mobile')
nasnet_metrics = evaluate_model(
    nasnet_model, test_loader, nasnet_ckpt,
    "NASNet-Mobile", tune_threshold=False)

"""**NASNet-Mobile Weight Fix:**

Force-delete a corrupt cached weight file and re-download from the Wayback
Machine. Run this cell only if NASNet weight loading fails with a
RuntimeError or EOFError on torch.load.
"""

# import os, subprocess

# ckpt_dir  = os.path.expanduser("~/.cache/torch/hub/checkpoints")
# ckpt_file = os.path.join(ckpt_dir, "nasnetamobile-7e03cead.pth")

# if os.path.exists(ckpt_file):
#     os.remove(ckpt_file)
#     print("🗑️ Deleted corrupt file")

# url = "https://web.archive.org/web/2024/http://data.lip6.fr/cadene/pretrainedmodels/nasnetamobile-7e03cead.pth"
# subprocess.run(["wget", "--no-check-certificate", "-q", "-O", ckpt_file, url], check=True)
# print(f"✅ {os.path.getsize(ckpt_file)/1024**2:.1f} MB downloaded")

"""**EfficientNet-Lite0:**"""

gc.collect(); torch.cuda.empty_cache()
train_loader, val_loader, test_loader = make_loaders(weighted_oversample=True)

effnet_model, _ = build_efficientnet_lite(
    lr=LR, dropout_rate=0.2, freeze_body=False)

head_params  = list(effnet_model.classifier.parameters())
head_ids     = {id(p) for p in head_params}
body_params  = [p for p in effnet_model.parameters() if id(p) not in head_ids]
effnet_opt   = torch.optim.AdamW([
    {"params": body_params, "lr": LR * 0.15, "weight_decay": 1e-3},
    {"params": head_params, "lr": LR,         "weight_decay": 5e-4},
])

effnet_sched = cosine_with_warmup_scheduler(
    effnet_opt, warmup_epochs=WARMUP_EPOCHS, total_epochs=EPOCHS)

effnet_class_weights = torch.tensor([1.5, 1.0, 2.5, 1.0], device=DEVICE)

effnet_model, effnet_history, effnet_ckpt, effnet_best_f1 = train_model(
    model           = effnet_model,
    optimizer       = effnet_opt,
    scheduler       = effnet_sched,
    train_loader    = train_loader,
    val_loader      = val_loader,
    model_name      = "efficientnet_lite0",
    epochs          = EPOCHS,
    patience        = 10,
    use_focal_loss  = True,
    gamma           = 2.0,
    label_smoothing = 0.01,
    use_mixup       = True,
    mixup_alpha     = 0.2,
    swa_start       = SWA_START_EPOCH,
    class_weights   = effnet_class_weights,
)

plot_history(effnet_history, 'EfficientNet-Lite0')
effnet_metrics = evaluate_model(
    effnet_model, test_loader, effnet_ckpt,
    "EfficientNet-Lite0", tune_threshold=True)

"""**Confusion Matrices — All Models:**"""

model_results = {
    "MobileNetV3-Large":  mobilenet_metrics,
    "NASNet-Mobile":      nasnet_metrics,
    "EfficientNet-Lite0": effnet_metrics,
}
short_names = [n.split()[0] for n in CLASS_NAMES.values()]

fig, axes = plt.subplots(1, 3, figsize=(21, 6))
fig.suptitle("Confusion Matrices — Held-out Test Set", fontsize=14)

for ax, (name, metrics) in zip(axes, model_results.items()):
    sns.heatmap(metrics["confusion_matrix"], annot=True, fmt="d",
                cmap="Blues", ax=ax,
                xticklabels=short_names, yticklabels=short_names, cbar=False)
    ax.set_title(
        f"{name}\nF1={metrics['f1']:.4f}  Acc={metrics['accuracy']:.4f}"
        f"  FPR_ND={metrics['fpr_nutrient_def']:.4f}",
        fontsize=10)
    ax.set_ylabel("True"); ax.set_xlabel("Predicted")

plt.tight_layout()
cm_path = os.path.join(META_DIR, "confusion_matrices_all_models.png")
plt.savefig(cm_path, dpi=120)
plt.show()
print(f"✅ Saved {cm_path}")

"""**Model Comparison:**"""

rows = []
for name, metrics in model_results.items():
    row = {
        "Model":        name,
        "Accuracy":     round(metrics["accuracy"],         4),
        "Precision":    round(metrics["precision"],        4),
        "Recall":       round(metrics["recall"],           4),
        "F1 (wtd)":     round(metrics["f1"],               4),
        "FPR NutriDef": round(metrics["fpr_nutrient_def"], 4),
    }
    for cls, f1v in metrics["per_class_f1"].items():
        row[f"F1 {cls.split()[0]}"] = f1v
    rows.append(row)

comparison_df = pd.DataFrame(rows).set_index("Model")

print("\n" + "="*75)
print("FINAL COMPARISON — TEST SET")
print("="*75)
print(comparison_df.to_string())
print("="*75)

per_class_df = pd.DataFrame({
    name: metrics["per_class_f1"]
    for name, metrics in model_results.items()
}).T

fig, ax = plt.subplots(figsize=(10, 5))
per_class_df.plot(kind="bar", ax=ax, colormap="Set2",
                  edgecolor="gray", linewidth=0.5)
ax.axhline(0.90, color="red", linestyle="--", alpha=0.5, label="Target F1=0.90")
ax.set_title("Per-Class F1 Score — All Models", fontsize=13)
ax.set_xticklabels(per_class_df.index, rotation=15, ha="right")
ax.set_ylabel("F1 Score"); ax.set_ylim(0, 1.05)
ax.legend(loc="lower right", fontsize=9); ax.grid(axis="y", alpha=0.4)
plt.tight_layout()
bar_path = os.path.join(META_DIR, "per_class_f1_comparison_enhanced.png")
plt.savefig(bar_path, dpi=120)
plt.show()
print(f"✅ Saved {bar_path}")

results_path = os.path.join(META_DIR, "classification_results_enhanced.csv")
comparison_df.reset_index().to_csv(results_path, index=False)
print(f"✅ Saved {results_path}")

print("\n🎉  Notebook 3 complete")
print("\nAll fixes applied:")
print("  1. FocalLoss — per-class weights [BLB=1.5, BS=1.0, ND=2.5, H=1.0]")
print("  2. train_model — consistent val criterion (plain CE always)")
print("  3. build_nasnet_mobile — SSL-bypass download for expired cert")
print("  4. evaluate_model — SWA AveragedModel unwrap fix")
print("  5. train_transform — ElasticTransform + RandomPerspective removed")
print("  6. EfficientNet — body LR=0.15x, dropout=0.2, gamma=1.0, patience=10")
print("\nOutputs:")
print(f"  {results_path}")
print(f"  {cm_path}")
print(f"  {bar_path}")
for tag in ["mobilenetv3_large", "nasnetamobile", "efficientnet_lite0"]:
    print(f"  {os.path.join(MODELS_DIR, f'best_{tag}.pth')}")