# -*- coding: utf-8 -*-
"""Ensemble (Final)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1co-j0koeZAO-08birGFVCrG3eVzlJ9yW

# **Ensemble**

This notebook loads the three classifiers and the UNet segmenter trained in Notebooks 2–3, builds a weighted-probability ensemble two different ways (raw images, and segmentation-masked images), finds ensemble weights two independent ways (gradient-based and brute-force), and reports final test-set numbers.

**Prerequisites:**
"""

!pip install timm==0.6.13 --quiet
!pip install pretrainedmodels --quiet
!pip install segmentation-models-pytorch albumentations --quiet
!pip install scipy --quiet

from google.colab import drive
drive.mount('/content/drive')

import gc, os, math, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from tqdm import tqdm
import cv2

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)
from scipy.optimize import minimize
from scipy.stats import pearsonr

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import torchvision.models as tv_models
import albumentations as A
from albumentations.pytorch import ToTensorV2

import timm
import pretrainedmodels
import segmentation_models_pytorch as smp

gc.collect()
torch.cuda.empty_cache()
print('Imports OK')
print('torch :', torch.__version__)
print('timm  :', timm.__version__)

"""**Configuration:**"""

PROJECT_ROOT = "/content/drive/MyDrive/thesis"

TRAIN_CSV = os.path.join(PROJECT_ROOT, "data/metadata/train.csv")
TEST_CSV  = os.path.join(PROJECT_ROOT, "data/metadata/test.csv")

MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
META_DIR   = os.path.join(PROJECT_ROOT, "data/metadata")
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(META_DIR,   exist_ok=True)

# Classifier checkpoints (Notebook 3)
MOBILENET_CKPT = os.path.join(MODELS_DIR, "best_mobilenetv3_large.pth")
NASNET_CKPT    = os.path.join(MODELS_DIR, "best_nasnetamobile.pth")
EFFNET_CKPT    = os.path.join(MODELS_DIR, "best_efficientnet_lite0.pth")

# Segmentation checkpoint (Notebook 2)
UNET_CKPT = os.path.join(MODELS_DIR, "best_unet_b5_scse_v2.pth")

IMG_SIZE_CLS = 224   # classifier input resolution
IMG_SIZE_SEG = 512   # UNet input/output resolution
BATCH_SIZE   = 32
NUM_CLASSES  = 4     # 0=bacterial 1=brown_spot 2=nutrient_def 3=healthy
NUM_WORKERS  = 2
RANDOM_STATE = 42

SEG_NUM_CLASSES = 4     # UNet: 0=background 1=bacterial 2=brown_spot 3=nutrient
SEG_ALPHA       = 0.35  # background-dimming strength, see Section 7
SEG_TTA         = True  # flip-TTA when running the UNet

# Weight search settings (Sections 14-15)
OPT_METHOD       = "L-BFGS-B"
OPT_MAX_ITER     = 500
BRUTE_FORCE_STEP = 0.05   # grid resolution for the exhaustive weight search

CLASS_NAMES = {
    0: "Bacterial Leaf Blight",
    1: "Brown Spot",
    2: "Nutrient Deficiency",
    3: "Healthy",
}
NUTRIENT_DEF_IDX = 2

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE      :", DEVICE)
print("IMG_SIZE_CLS:", IMG_SIZE_CLS, " IMG_SIZE_SEG:", IMG_SIZE_SEG)
print("BATCH_SIZE  :", BATCH_SIZE, " NUM_CLASSES:", NUM_CLASSES)

"""**Load Metadata & Recreate the Train/Val/Test Split:**

Uses the same `RANDOM_STATE=42` stratified split as Notebook 3, so `val_df` / `test_df` here are pixel-for-pixel the same samples the classifiers were validated/tested on — required for the ensemble weights and test metrics to be comparable to the single-model numbers.
"""

train_full_df = pd.read_csv(TRAIN_CSV)
test_df       = pd.read_csv(TEST_CSV)

train_full_df["label"] = train_full_df["class_id"] - 1   # 1-indexed -> 0-indexed
test_df["label"]       = test_df["class_id"] - 1

train_df, val_df = train_test_split(
    train_full_df, test_size=0.15,
    stratify=train_full_df["label"], random_state=RANDOM_STATE
)
train_df = train_df.reset_index(drop=True)
val_df   = val_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

print(f"Train: {len(train_df)}  Val: {len(val_df)}  Test: {len(test_df)}")
print("\nVal class distribution:")
print(val_df["label"].value_counts().sort_index().rename(CLASS_NAMES))

"""**Metrics Utilities:**"""

def compute_metrics(all_preds, all_labels, print_report=False, print_cm=False):
    preds  = np.array(all_preds)
    labels = np.array(all_labels)
    mask   = labels != -1
    preds, labels = preds[mask], labels[mask]

    acc  = accuracy_score(labels, preds)
    prec = precision_score(labels, preds, average="weighted", zero_division=0)
    rec  = recall_score(labels,   preds, average="weighted", zero_division=0)
    f1   = f1_score(labels,       preds, average="weighted", zero_division=0)
    f1_per = f1_score(labels,     preds, average=None,       zero_division=0)

    cm     = confusion_matrix(labels, preds, labels=list(range(NUM_CLASSES)))
    nd_idx = NUTRIENT_DEF_IDX
    fp_nd  = cm[:, nd_idx].sum() - cm[nd_idx, nd_idx]
    tn_nd  = cm.sum() - cm[nd_idx, :].sum() - cm[:, nd_idx].sum() + cm[nd_idx, nd_idx]
    fpr_nd = float(fp_nd) / float(fp_nd + tn_nd) if (fp_nd + tn_nd) > 0 else 0.0

    if print_cm:
        print("\nConfusion Matrix:")
        print(pd.DataFrame(cm,
            index=[f"True: {CLASS_NAMES[i]}" for i in range(NUM_CLASSES)],
            columns=[f"Pred: {CLASS_NAMES[i]}" for i in range(NUM_CLASSES)]).to_string())
    if print_report:
        print("\nClassification Report:")
        print(classification_report(labels, preds, labels=list(range(NUM_CLASSES)),
              target_names=list(CLASS_NAMES.values()), digits=4, zero_division=0))

    return {
        "accuracy": acc, "precision": prec, "recall": rec, "f1": f1,
        "fpr_nutrient_def": fpr_nd,
        "per_class_f1": {CLASS_NAMES[i]: round(float(v), 4) for i, v in enumerate(f1_per)},
        "confusion_matrix": cm, "all_preds": preds, "all_labels": labels,
    }

def print_metrics(metrics, title="RESULTS"):
    print(f"\n── {title} ──────────────────────────────────────────────")
    print(f"  Accuracy                  : {metrics['accuracy']:.4f}")
    print(f"  Precision (weighted)      : {metrics['precision']:.4f}")
    print(f"  Recall    (weighted)      : {metrics['recall']:.4f}")
    print(f"  F1        (weighted)      : {metrics['f1']:.4f}")
    print(f"  FPR - Nutrient Deficiency : {metrics['fpr_nutrient_def']:.4f}")
    print("\n  Per-class F1:")
    for cls, f1v in metrics["per_class_f1"].items():
        status = "OK " if f1v >= 0.90 else "low"
        print(f"    [{status}] {cls:<30}: {f1v:.4f}")

print("compute_metrics() / print_metrics() ready")

"""**Transforms:**

Two separate pipelines because the classifiers and the UNet were trained at different resolutions: `val_transform` (224px, torchvision) feeds the classifiers, `seg_transform` (512px, Albumentations) feeds the UNet.
"""

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

val_transform = T.Compose([
    T.ToPILImage(),
    T.Resize((IMG_SIZE_CLS, IMG_SIZE_CLS)),
    T.ToTensor(),
    T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])

seg_transform = A.Compose([
    A.Resize(IMG_SIZE_SEG, IMG_SIZE_SEG),
    A.Normalize(),
    ToTensorV2()
])

print("Transforms ready")

"""**Dataset — Mode A (Raw Images):**

Plain image loader, no segmentation involved.
"""

class ClassificationDataset(Dataset):
    def __init__(self, df, transform=None):
        self.df, self.transform = df.reset_index(drop=True), transform
        self._warned = set()

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row, label = self.df.iloc[idx], int(self.df.iloc[idx]["label"])
        image = cv2.imread(row["image_path"])
        if image is None:
            if row["image_path"] not in self._warned:
                print(f"\nUnreadable: {row['image_path']}")
                self._warned.add(row["image_path"])
            return torch.zeros(3, IMG_SIZE_CLS, IMG_SIZE_CLS, dtype=torch.float32), -1
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        if self.transform:
            image = self.transform(image)
        return image, label

print("ClassificationDataset ready")

"""**Dataset — Mode B (Segmentation-Guided Images):**

For each image the UNet predicts a per-pixel softmax over 4 segmentation classes (`0=background, 1=bacterial, 2=brown_spot, 3=nutrient_def`). Two things are derived from that:

**(a) Background dimming (the actual classifier input).** Per-pixel foreground probability:
$$fg(p) = 1 - P_{seg}(\text{background} \mid p)$$
The image is reweighted pixel-by-pixel:
$$\text{weight}(p) = (1-\alpha) + \alpha \cdot fg(p), \qquad \text{masked}(p) = \text{image}(p) \cdot \text{weight}(p)$$
with $\alpha =$ `SEG_ALPHA` (0.35). $\alpha=0$ leaves the image untouched; $\alpha=1$ would zero out background entirely. The masked image is what actually gets resized to 224px and passed to the classifiers.

**(b) Segmentation prior (diagnostic only).** Take the arg-max segmentation class per pixel, count pixels per class, remap to the classifier's label space (`background→Healthy, bacterial→0, brown_spot→1, nutrient_def→2`), normalise to a distribution. This `seg_prior` is **not** fed into the classifiers — it's logged so Section 20 can sanity-check whether the UNet's own class guess agrees with ground truth.
"""

class SegmentedClassificationDataset(Dataset):
    """
    Returns (cls_image, label, seg_prior):
      cls_image : (3, IMG_SIZE_CLS, IMG_SIZE_CLS) -- seg-masked, normalised
      label     : int, 0-indexed
      seg_prior : (NUM_CLASSES,) float tensor -- UNet class distribution (diagnostic)
    """
    def __init__(self, df, seg_model, transform=None, alpha=SEG_ALPHA, tta=SEG_TTA):
        self.df, self.seg_model, self.transform = df.reset_index(drop=True), seg_model, transform
        self.alpha, self.tta = alpha, tta
        self._warned = set()

    def __len__(self):
        return len(self.df)

    def _seg_inference(self, image_rgb_512):
        """UNet (+ optional flip-TTA) on a (512,512,3) uint8 array -> softmax probs (4,512,512)."""
        def _fwd(img_np):
            aug = seg_transform(image=img_np)
            x = aug["image"].unsqueeze(0).to(DEVICE)
            with torch.no_grad(), torch.amp.autocast("cuda"):
                logit = self.seg_model(x)
            return torch.softmax(logit.squeeze(0), dim=0)

        probs = _fwd(image_rgb_512)
        if self.tta:
            hf = _fwd(np.fliplr(image_rgb_512).copy())
            probs = probs + torch.flip(hf, [2])
            vf = _fwd(np.flipud(image_rgb_512).copy())
            probs = probs + torch.flip(vf, [1])
            probs = probs / 3.0
        return probs.cpu()

    def _seg_prior(self, probs):
        per_pixel_class = probs.argmax(dim=0).numpy()
        pixel_counts = np.bincount(per_pixel_class.flatten(), minlength=SEG_NUM_CLASSES)
        seg_to_cls = [3, 0, 1, 2]   # bg->healthy, bacterial->0, brown_spot->1, nutrient->2
        prior = np.zeros(NUM_CLASSES, dtype=np.float32)
        for seg_idx, cls_idx in enumerate(seg_to_cls):
            prior[cls_idx] = pixel_counts[seg_idx]
        prior = prior / (prior.sum() + 1e-8)
        return torch.from_numpy(prior).float()

    def _apply_mask(self, image_rgb_512, probs):
        fg_prob = 1.0 - probs[0].numpy()
        weight = (1.0 - self.alpha) + self.alpha * fg_prob
        weight = weight[:, :, np.newaxis]
        masked = (image_rgb_512.astype(np.float32) * weight).clip(0, 255)
        return masked.astype(np.uint8)

    def __getitem__(self, idx):
        row, label = self.df.iloc[idx], int(self.df.iloc[idx]["label"])
        image_bgr = cv2.imread(row["image_path"])
        if image_bgr is None:
            if row["image_path"] not in self._warned:
                print(f"\nUnreadable: {row['image_path']}")
                self._warned.add(row["image_path"])
            dummy_prior = torch.zeros(NUM_CLASSES); dummy_prior[label] = 1.0
            return torch.zeros(3, IMG_SIZE_CLS, IMG_SIZE_CLS), -1, dummy_prior

        image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
        image_512 = cv2.resize(image_rgb, (IMG_SIZE_SEG, IMG_SIZE_SEG))

        self.seg_model.eval()
        probs = self._seg_inference(image_512)
        seg_prior = self._seg_prior(probs)
        masked_512 = self._apply_mask(image_512, probs)

        cls_image = (self.transform or val_transform)(masked_512)
        return cls_image, label, seg_prior

print("SegmentedClassificationDataset ready")

"""**Model Factory:**

Architecture definitions matching Notebook 3 exactly (so `state_dict` keys line up with the saved checkpoints), plus the UNet segmenter from Notebook 2.
"""

def count_params(model):
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    return total, trainable

def build_mobilenetv3(num_classes=NUM_CLASSES):
    model = tv_models.mobilenet_v3_large(pretrained=True)
    model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    return model.to(DEVICE)

def build_nasnet_mobile(num_classes=NUM_CLASSES):
    import subprocess
    ckpt_dir = os.path.expanduser("~/.cache/torch/hub/checkpoints")
    ckpt_file = os.path.join(ckpt_dir, "nasnetamobile-7e03cead.pth")
    os.makedirs(ckpt_dir, exist_ok=True)

    needs_download = (not os.path.exists(ckpt_file)
                       or os.path.getsize(ckpt_file) < 20 * 1024 * 1024)
    if needs_download:
        if os.path.exists(ckpt_file):
            os.remove(ckpt_file)
        url = ("https://web.archive.org/web/2024/http://data.lip6.fr/cadene/"
               "pretrainedmodels/nasnetamobile-7e03cead.pth")
        subprocess.run(["wget", "--no-check-certificate", "-q", "-O", ckpt_file, url], check=True)

    model = pretrainedmodels.__dict__["nasnetamobile"](num_classes=1000, pretrained="imagenet")
    in_features = model.last_linear.in_features
    model.last_linear = nn.Sequential(nn.Dropout(0.2), nn.Linear(in_features, num_classes))
    return model.to(DEVICE)

def build_efficientnet_lite(num_classes=NUM_CLASSES, dropout_rate=0.3):
    model = timm.create_model("efficientnet_lite0", pretrained=False,
                               num_classes=num_classes, drop_rate=dropout_rate)
    return model.to(DEVICE)

def build_unet_b5():
    model = smp.Unet(encoder_name="timm-efficientnet-b5", encoder_weights=None,
                      in_channels=3, classes=SEG_NUM_CLASSES,
                      activation=None, decoder_attention_type="scse")
    return model.to(DEVICE)

print("Model factory ready")

"""**Load Trained Checkpoints:**

Loads the best-F1 checkpoint for each of the three classifiers (from Notebook 3) and the best-Dice checkpoint for the UNet (from Notebook 2). All models are set to `eval()` immediately — nothing in this notebook trains anything.
"""

def load_classifier(build_fn, ckpt_path, model_name):
    assert os.path.exists(ckpt_path), f"Checkpoint not found: {ckpt_path}"
    model = build_fn()
    ckpt = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()
    print(f"Loaded {model_name}  (epoch {ckpt['epoch']}, best val F1={ckpt['best_f1']:.4f})")
    return model

mobilenet_model = load_classifier(build_mobilenetv3,       MOBILENET_CKPT, "MobileNetV3-Large")
nasnet_model    = load_classifier(build_nasnet_mobile,     NASNET_CKPT,    "NASNet-Mobile")
effnet_model    = load_classifier(build_efficientnet_lite, EFFNET_CKPT,    "EfficientNet-Lite0")

cls_models = {
    "MobileNetV3-Large": mobilenet_model,
    "NASNet-Mobile": nasnet_model,
    "EfficientNet-Lite0": effnet_model,
}
model_names = list(cls_models.keys())
print(f"\n{len(cls_models)} classifiers loaded.")

assert os.path.exists(UNET_CKPT), "UNet checkpoint not found"
ckpt = torch.load(UNET_CKPT, map_location=DEVICE, weights_only=False)
unet_model = build_unet_b5()
unet_model.load_state_dict(ckpt["model_state_dict"])
unet_model.eval()
print(f"Loaded UNet  (epoch {ckpt.get('epoch', '?')}, best Dice {ckpt.get('best_dice', '?')})")

"""**Collect Logits — Mode A (No Segmentation):**

Runs all three classifiers over the raw (unmasked) val/test images once and caches the logits, so every weighting experiment below is just arithmetic on cached arrays instead of re-running the networks.
"""

def collect_logits_no_seg(df, models_dict, batch_size=BATCH_SIZE):
    dataset = ClassificationDataset(df, transform=val_transform)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False,
                         num_workers=NUM_WORKERS, pin_memory=True)

    logits_dict = {name: [] for name in models_dict}
    true_labels = []

    for images, labels in tqdm(loader, desc="Collecting logits (no seg)", leave=False):
        images = images.to(DEVICE)
        valid = labels != -1
        if valid.sum() == 0:
            continue
        true_labels.extend(labels[valid].numpy())
        for name, model in models_dict.items():
            with torch.no_grad(), torch.amp.autocast("cuda"):
                out = model(images[valid])
            logits_dict[name].append(out.cpu().float().numpy())

    for name in logits_dict:
        logits_dict[name] = np.concatenate(logits_dict[name], axis=0)
    return logits_dict, np.array(true_labels)

print("Collecting validation set logits...")
val_logits_noseg, val_labels_noseg = collect_logits_no_seg(val_df, cls_models)

print("Collecting test set logits...")
test_logits_noseg, test_labels_noseg = collect_logits_no_seg(test_df, cls_models)

print(f"\nVal samples: {len(val_labels_noseg)}   Test samples: {len(test_labels_noseg)}")

"""**Collect Logits — Mode B (With Segmentation):**

Same idea, but each image is first passed through the UNet and background-dimmed (Section 7) before the classifiers see it. This is the slow cell — UNet + 3x TTA forward pass per image, batch size forced to 1.
"""

def collect_logits_with_seg(df, models_dict, seg_model, batch_size=BATCH_SIZE):
    dataset = SegmentedClassificationDataset(df, seg_model=seg_model, transform=val_transform)
    loader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=0)

    logits_dict = {name: [] for name in models_dict}
    seg_priors, true_labels = [], []

    for cls_image, label, seg_prior in tqdm(loader, desc="Collecting logits (with seg)"):
        cls_image = cls_image.squeeze(0).to(DEVICE)
        label_val = label.item()
        if label_val == -1:
            continue
        for name, model in models_dict.items():
            with torch.no_grad(), torch.amp.autocast("cuda"):
                out = model(cls_image.unsqueeze(0))
            logits_dict[name].append(out.cpu().float().numpy()[0])
        seg_priors.append(seg_prior.squeeze(0).numpy())
        true_labels.append(label_val)

    for name in logits_dict:
        logits_dict[name] = np.array(logits_dict[name])
    seg_priors, true_labels = np.array(seg_priors), np.array(true_labels)

    print(f"\nCollected {len(true_labels)} samples")
    for name, arr in logits_dict.items():
        if len(arr) != len(true_labels):
            raise ValueError(f"MISMATCH: {name} has {len(arr)} but labels have {len(true_labels)}")
    return logits_dict, seg_priors, true_labels

print("This will take a few minutes (UNet inference per image)...")
print("Collecting validation set logits...")
val_logits_seg, val_seg_priors, val_labels_seg = collect_logits_with_seg(val_df, cls_models, unet_model)

print("\nCollecting test set logits...")
test_logits_seg, test_seg_priors, test_labels_seg = collect_logits_with_seg(test_df, cls_models, unet_model)

"""**Individual Model Baselines (Mode A):**

Per-model test performance with no ensembling at all — the number every ensemble result below has to beat.
"""

def softmax_np(logits):
    e = np.exp(logits - logits.max(axis=-1, keepdims=True))
    return e / e.sum(axis=-1, keepdims=True)

individual_metrics_A = {}
for name, logits in test_logits_noseg.items():
    preds = softmax_np(logits).argmax(axis=1)
    m = compute_metrics(preds, test_labels_noseg)
    individual_metrics_A[name] = m
    print(f"\n{name}")
    print(f"  Accuracy: {m['accuracy']:.4f}  F1: {m['f1']:.4f}  FPR_ND: {m['fpr_nutrient_def']:.4f}")

"""**Ensemble Math — How the Final Probability Is Computed:**

This is the core logic everything below builds on.

Each of the $M=3$ classifiers (MobileNetV3, NASNet-Mobile, EfficientNet-Lite0) outputs raw logits $z_m(x) \in \mathbb{R}^4$ for an input image $x$.

**Step 1 — Per-model probabilities (softmax):**
$$p_{m,c}(x) = \frac{\exp(z_{m,c}(x))}{\sum_{c'=1}^{4} \exp(z_{m,c'}(x))}$$

**Step 2 — Weighted fusion across models:**
$$P_{ens,c}(x) = \sum_{m=1}^{M} w_m \, p_{m,c}(x), \qquad w_m \ge 0, \ \ \sum_{m=1}^{M} w_m = 1$$

**Step 3 — Final class prediction:**
$$\hat{y} = \arg\max_c \; P_{ens,c}(x)$$

The only unknowns are the $M$ weights $w_m$ — how much to trust each model. **Two independent methods** are used to find them, both fit on the **validation set only**; the test set is touched once per mode, purely for reporting.

**Weight-Finding Method 1 — Gradient-Based Optimisation:**

Weights must live on the probability simplex ($w_m \ge 0$, $\sum_m w_m = 1$). Rather than constrain the optimiser directly, we reparameterise: optimise unconstrained "raw" scores $\theta_m \in \mathbb{R}$ and pass them through a softmax to get valid weights:
$$w_m = \frac{\exp(\theta_m)}{\sum_{m'} \exp(\theta_{m'})}$$

`scipy.optimize.minimize` (L-BFGS-B) then searches $\theta$ to minimise the *negative* weighted F1 on the validation set:
$$\theta^{*} = \arg\min_{\theta} \; -F1_{weighted}\Big(\arg\max_c P_{ens,c}(x;\,w(\theta)) \;;\; y_{val}\Big)$$

**Caveat:** because the final `argmax` makes F1 a step function of the weights, the "gradient" L-BFGS-B follows is only a local, noisy approximation — it can stall in a flat region. That's why Method 2 exists as a cross-check.
"""

def weighted_ensemble_probs(logits_list, weights):
    """logits_list: list of (N,C) arrays, weights: (M,) array summing to 1 -> (N,C) probs."""
    probs = np.stack([softmax_np(l) for l in logits_list], axis=0)      # (M, N, C)
    w = np.array(weights)[:, np.newaxis, np.newaxis]                     # (M, 1, 1)
    return (probs * w).sum(axis=0)                                      # (N, C)

def neg_f1_objective(raw_weights, logits_list, true_labels):
    weights = np.exp(raw_weights) / np.exp(raw_weights).sum()
    ens_prob = weighted_ensemble_probs(logits_list, weights)
    preds = ens_prob.argmax(axis=1)
    return -f1_score(true_labels, preds, average="weighted", zero_division=0)

def optimise_weights(logits_list, true_labels, n_models, method=OPT_METHOD):
    """Finds w on the simplex that maximises weighted F1 via softmax-reparameterised L-BFGS-B."""
    x0 = np.zeros(n_models)
    result = minimize(neg_f1_objective, x0, args=(logits_list, true_labels),
                       method=method, options={"maxiter": OPT_MAX_ITER, "ftol": 1e-9})
    opt_weights = np.exp(result.x) / np.exp(result.x).sum()
    best_f1 = -result.fun
    return opt_weights, best_f1

print("optimise_weights() ready (Method 1 - gradient-based)")

"""**Weight-Finding Method 2 — Brute-Force Grid Search:**

With only $M=3$ models the simplex is 2-dimensional ($w_3 = 1-w_1-w_2$), so it's cheap to search exhaustively instead of trusting a local optimiser. We grid $(w_1, w_2)$ at step size `BRUTE_FORCE_STEP`, discard invalid combinations, and evaluate validation weighted-F1 directly for every point:
$$w^{*} = \arg\max_{w \,\in\, \text{grid}} \; F1_{weighted}\Big(\arg\max_c P_{ens,c}(x;w) \;;\; y_{val}\Big)$$
"""

def brute_force_weights(logits_list, true_labels, step=BRUTE_FORCE_STEP, verbose=False):
    best_f1, best_weights = -1, None
    weights_range = np.arange(0, 1.0 + step, step)

    for w1 in weights_range:
        for w2 in weights_range:
            w3 = 1 - w1 - w2
            if w3 < -1e-6 or w3 > 1 + 1e-6:
                continue
            weights = np.clip([w1, w2, w3], 0, 1)
            weights = weights / weights.sum()

            ens_prob = weighted_ensemble_probs(logits_list, weights)
            preds = ens_prob.argmax(axis=1)
            f1 = f1_score(true_labels, preds, average="weighted", zero_division=0)

            if f1 > best_f1:
                best_f1, best_weights = f1, weights
                if verbose:
                    print(f"  new best: w={np.round(weights, 3)}  F1={f1:.4f}")

    return best_weights, best_f1

print("brute_force_weights() ready (Method 2 - exhaustive grid search)")

"""**Mode A — No-Segmentation Ensemble Results:**

Runs both weight-finding methods on the Mode A (raw image) validation logits, compares them, and evaluates the better one on the held-out test set.
"""

val_logits_list_noseg  = list(val_logits_noseg.values())
test_logits_list_noseg = list(test_logits_noseg.values())

uniform_w = np.array([1/3, 1/3, 1/3])
uniform_preds_val = weighted_ensemble_probs(val_logits_list_noseg, uniform_w).argmax(axis=1)
uniform_f1_val_A = f1_score(val_labels_noseg, uniform_preds_val, average="weighted")

print("Method 1 (gradient)...")
grad_w_A, grad_f1_val_A = optimise_weights(val_logits_list_noseg, val_labels_noseg, n_models=3)

print("Method 2 (brute force)...")
brute_w_A, brute_f1_val_A = brute_force_weights(val_logits_list_noseg, val_labels_noseg)

print("\nValidation F1 by method (Mode A):")
print(f"  Uniform   [1/3, 1/3, 1/3]            : {uniform_f1_val_A:.4f}")
print(f"  Gradient  {np.round(grad_w_A, 3)}            : {grad_f1_val_A:.4f}")
print(f"  Brute force {np.round(brute_w_A, 3)}          : {brute_f1_val_A:.4f}")

# Carry forward whichever validates higher (brute force, by construction, is >= gradient)
best_weights_A = brute_w_A if brute_f1_val_A >= grad_f1_val_A else grad_w_A
print(f"\nSelected Mode A weights -> {dict(zip(model_names, np.round(best_weights_A, 3)))}")

test_probs_A = weighted_ensemble_probs(test_logits_list_noseg, best_weights_A)
test_preds_A = test_probs_A.argmax(axis=1)
metrics_noseg = compute_metrics(test_preds_A, test_labels_noseg)
metrics_uni_noseg = compute_metrics(
    weighted_ensemble_probs(test_logits_list_noseg, uniform_w).argmax(axis=1), test_labels_noseg)

print_metrics(metrics_uni_noseg, "Mode A - Uniform Ensemble (Test)")
print_metrics(metrics_noseg,     "Mode A - Selected-Weight Ensemble (Test)")

"""**Mode B — With-Segmentation Ensemble Results:**

Identical procedure to Section 16, but on the segmentation-masked logits collected in Section 11.
"""

val_logits_list_seg  = list(val_logits_seg.values())
test_logits_list_seg = list(test_logits_seg.values())

uniform_preds_val_seg = weighted_ensemble_probs(val_logits_list_seg, uniform_w).argmax(axis=1)
uniform_f1_val_B = f1_score(val_labels_seg, uniform_preds_val_seg, average="weighted")

print("Method 1 (gradient)...")
grad_w_B, grad_f1_val_B = optimise_weights(val_logits_list_seg, val_labels_seg, n_models=3)

print("Method 2 (brute force)...")
brute_w_B, brute_f1_val_B = brute_force_weights(val_logits_list_seg, val_labels_seg)

print("\nValidation F1 by method (Mode B):")
print(f"  Uniform     [1/3, 1/3, 1/3]          : {uniform_f1_val_B:.4f}")
print(f"  Gradient    {np.round(grad_w_B, 3)}            : {grad_f1_val_B:.4f}")
print(f"  Brute force {np.round(brute_w_B, 3)}          : {brute_f1_val_B:.4f}")

best_weights_B = brute_w_B if brute_f1_val_B >= grad_f1_val_B else grad_w_B
print(f"\nSelected Mode B weights -> {dict(zip(model_names, np.round(best_weights_B, 3)))}")

test_probs_B = weighted_ensemble_probs(test_logits_list_seg, best_weights_B)
test_preds_B = test_probs_B.argmax(axis=1)
metrics_seg = compute_metrics(test_preds_B, test_labels_seg)
metrics_uni_seg = compute_metrics(
    weighted_ensemble_probs(test_logits_list_seg, uniform_w).argmax(axis=1), test_labels_seg)

print_metrics(metrics_uni_seg, "Mode B - Uniform Ensemble (Test)")
print_metrics(metrics_seg,     "Mode B - Selected-Weight Ensemble (Test)")

best_weights_seg = best_weights_B  # used again in the Section 22 demo

"""**Final Comparison — Individuals vs Mode A vs Mode B:**

One table, one weights chart, one F1 chart, one confusion-matrix pair.
"""

best_single_name = max(individual_metrics_A.items(), key=lambda x: x[1]["f1"])[0]
best_single_f1 = individual_metrics_A[best_single_name]["f1"]

rows = []
for name, m in individual_metrics_A.items():
    rows.append({"Method": name, "Accuracy": m["accuracy"], "F1": m["f1"],
                 "FPR_NutriDef": m["fpr_nutrient_def"]})
rows.append({"Method": "Ensemble-A (No Segmentation)", "Accuracy": metrics_noseg["accuracy"],
             "F1": metrics_noseg["f1"], "FPR_NutriDef": metrics_noseg["fpr_nutrient_def"]})
rows.append({"Method": "Ensemble-B (With Segmentation)", "Accuracy": metrics_seg["accuracy"],
             "F1": metrics_seg["f1"], "FPR_NutriDef": metrics_seg["fpr_nutrient_def"]})

comparison_df = pd.DataFrame(rows).set_index("Method").round(4)
print(comparison_df.to_string())

print(f"\nBest single model      : {best_single_name}  F1={best_single_f1:.4f}")
print(f"Ensemble-A improvement : {(metrics_noseg['f1']-best_single_f1)*100:+.2f} pp")
print(f"Ensemble-B improvement : {(metrics_seg['f1']-best_single_f1)*100:+.2f} pp")
print(f"Segmentation effect (B vs A): {(metrics_seg['f1']-metrics_noseg['f1'])*100:+.2f} pp")

# ── weights + F1 bar charts ──────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

x = np.arange(len(model_names)); width = 0.35
axes[0].bar(x - width/2, best_weights_A, width, label="Mode A (No Seg)", color="steelblue")
axes[0].bar(x + width/2, best_weights_B, width, label="Mode B (With Seg)", color="coral")
axes[0].axhline(1/3, color="gray", linestyle="--", alpha=0.5, label="Uniform")
axes[0].set_xticks(x); axes[0].set_xticklabels(model_names, rotation=15, ha="right")
axes[0].set_ylabel("Weight"); axes[0].set_title("Selected Ensemble Weights"); axes[0].legend()

methods = ["Best Single", "Ensemble-A", "Ensemble-B"]
f1s = [best_single_f1, metrics_noseg["f1"], metrics_seg["f1"]]
bars = axes[1].bar(methods, f1s, color=["gray", "steelblue", "coral"], edgecolor="black")
for bar, f1v in zip(bars, f1s):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.005, f"{f1v:.4f}",
                 ha="center", fontsize=10, fontweight="bold")
axes[1].set_ylabel("F1 (weighted)"); axes[1].set_title("Performance Comparison")
axes[1].set_ylim(min(f1s)-0.05, max(f1s)+0.03)

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "mode_comparison.png"), dpi=120, bbox_inches="tight")
plt.show()

# ── confusion matrices ───────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Confusion Matrices: Ensemble Comparison", fontsize=14)
short_names = [n.split()[0] for n in CLASS_NAMES.values()]

sns.heatmap(metrics_noseg["confusion_matrix"], annot=True, fmt="d", cmap="Blues", ax=axes[0],
            xticklabels=short_names, yticklabels=short_names)
axes[0].set_title(f"Mode A (No Segmentation)\nF1={metrics_noseg['f1']:.4f}")
axes[0].set_ylabel("True"); axes[0].set_xlabel("Predicted")

sns.heatmap(metrics_seg["confusion_matrix"], annot=True, fmt="d", cmap="Blues", ax=axes[1],
            xticklabels=short_names, yticklabels=short_names)
axes[1].set_title(f"Mode B (With Segmentation)\nF1={metrics_seg['f1']:.4f}")
axes[1].set_ylabel("True"); axes[1].set_xlabel("Predicted")

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "confusion_matrices_comparison.png"), dpi=120)
plt.show()

"""**Model Diversity Diagnostics:**

Why does (or doesn't) ensembling help? Checks pairwise prediction agreement, logit correlation, complementary errors (cases where a weaker model is right and the strongest model is wrong), confidence correlation, and each model's most common confusions. High agreement + high correlation across all three models is the signature of an ensemble with little to gain — the weights above will end up close to uniform in that case.
"""

print("1. Prediction agreement between models:")
for i, name1 in enumerate(model_names):
    preds1 = softmax_np(test_logits_noseg[name1]).argmax(axis=1)
    for name2 in model_names[i+1:]:
        preds2 = softmax_np(test_logits_noseg[name2]).argmax(axis=1)
        print(f"  {name1} vs {name2}: {(preds1 == preds2).mean():.2%} agreement")

print("\n2. Logit correlation:")
for i, name1 in enumerate(model_names):
    for name2 in model_names[i+1:]:
        r = pearsonr(test_logits_noseg[name1].flatten(), test_logits_noseg[name2].flatten())[0]
        print(f"  {name1} vs {name2}: r={r:.4f}")

print("\n3. Complementary predictions (where the best model is wrong but another is right):")
best_model = model_names[0]
best_preds = softmax_np(test_logits_noseg[best_model]).argmax(axis=1)
best_wrong = best_preds != test_labels_noseg
for name in model_names[1:]:
    other_preds = softmax_np(test_logits_noseg[name]).argmax(axis=1)
    complementary = best_wrong & (other_preds == test_labels_noseg)
    fix_rate = complementary.sum() / max(best_wrong.sum(), 1)
    print(f"  {name} vs {best_model}: fixes {fix_rate:.1%} of {best_model}\'s {best_wrong.sum()} errors "
          f"({complementary.sum()} samples)")

print("\n4. Confidence correlation (max softmax probability):")
for i, name1 in enumerate(model_names):
    conf1 = softmax_np(test_logits_noseg[name1]).max(axis=1)
    for name2 in model_names[i+1:]:
        conf2 = softmax_np(test_logits_noseg[name2]).max(axis=1)
        print(f"  {name1} vs {name2}: r={pearsonr(conf1, conf2)[0]:.4f}")

print("\n5. Most common per-model confusions:")
for name in model_names:
    preds = softmax_np(test_logits_noseg[name]).argmax(axis=1)
    wrong = preds != test_labels_noseg
    if wrong.sum() == 0:
        continue
    err_cm = confusion_matrix(test_labels_noseg[wrong], preds[wrong])
    print(f"\n  {name}:")
    for t in range(NUM_CLASSES):
        for p in range(NUM_CLASSES):
            if t != p and err_cm[t, p] > 0:
                print(f"    {CLASS_NAMES[t]} -> {CLASS_NAMES[p]}: {err_cm[t, p]}x")

"""**Segmentation Quality Diagnostics:**

Checks whether the UNet's own pixel-class distribution (`seg_prior`, Section 7) actually points at the right disease — independent of how the classifiers perform on the masked images. Useful for telling apart "the UNet is wrong" from "the UNet is right but masking still hurts the classifiers."
"""

seg_pred_classes = val_seg_priors.argmax(axis=1)
true_classes = val_labels_seg

seg_accuracy = (seg_pred_classes == true_classes).mean()
print(f"Seg-prior accuracy (val): {seg_accuracy:.4f}")

print("\nPer-class seg-prior accuracy:")
for c in range(NUM_CLASSES):
    mask = true_classes == c
    if mask.sum() > 0:
        print(f"  {CLASS_NAMES[c]}: {(seg_pred_classes[mask] == c).mean():.4f}  ({mask.sum()} samples)")

print("\nConfusion matrix (seg prior vs true label):")
seg_cm_matrix = confusion_matrix(true_classes, seg_pred_classes, labels=range(NUM_CLASSES))
print(pd.DataFrame(seg_cm_matrix,
      index=[f"True: {CLASS_NAMES[i]}" for i in range(NUM_CLASSES)],
      columns=[f"Seg Pred: {CLASS_NAMES[i]}" for i in range(NUM_CLASSES)]).to_string())

print("\nSeg-prior class distribution vs ground truth:")
for c in range(NUM_CLASSES):
    print(f"  {CLASS_NAMES[c]}: predicted {(seg_pred_classes==c).mean()*100:.1f}%  "
          f"true {(true_classes==c).mean()*100:.1f}%")

print("\nForeground-probability mass per true class (higher = UNet more confident it found disease):")
for c in range(NUM_CLASSES):
    mask = true_classes == c
    if mask.sum() == 0:
        continue
    fg_prob = 1 - val_seg_priors[mask][:, 0]
    print(f"  {CLASS_NAMES[c]}: mean fg prob={fg_prob.mean():.4f}  std={fg_prob.std():.4f}")

"""**Lighting Conditions Validation:**"""

# Full test set (all backgrounds) under each lighting condition
LIGHTING_CSVS = {
    "morning_backlight": os.path.join(META_DIR, "test_morning_backlight.csv"),
    "noon_harsh_sun":    os.path.join(META_DIR, "test_noon_harsh_sun.csv"),
    "overcast":          os.path.join(META_DIR, "test_overcast.csv"),
    "low_light":         os.path.join(META_DIR, "test_low_light.csv"),
}

# Field-background subset: normal (unmodified ground-truth images) + 4 lit variants
FIELD_BG_CSVS = {
    "normal_field":      os.path.join(META_DIR, "test_field_bg.csv"),
    "morning_backlight": os.path.join(META_DIR, "test_field_bg_morning_backlight.csv"),
    "noon_harsh_sun":    os.path.join(META_DIR, "test_field_bg_noon_harsh_sun.csv"),
    "overcast":          os.path.join(META_DIR, "test_field_bg_overcast.csv"),
    "low_light":         os.path.join(META_DIR, "test_field_bg_low_light.csv"),
}

# Human-readable labels (used in charts and print statements)
COND_DISPLAY = {
    "original":          "Original",
    "normal_field":      "Normal Field",
    "morning_backlight": "Morning Backlight",
    "noon_harsh_sun":    "Noon Harsh Sun",
    "overcast":          "Overcast",
    "low_light":         "Low Light",
}


def load_test_df(csv_path):
    df = pd.read_csv(csv_path)
    df["label"] = df["class_id"] - 1   # 1-indexed → 0-indexed
    return df.reset_index(drop=True)


lighting_dfs, field_bg_dfs, _missing = {}, {}, []

print("Loading full lighting-condition CSVs:")
for name, path in LIGHTING_CSVS.items():
    if os.path.exists(path):
        lighting_dfs[name] = load_test_df(path)
        print(f"  [✓] {name:<22}  {len(lighting_dfs[name]):4d} samples")
    else:
        _missing.append(path)
        print(f"  [✗] {name:<22}  NOT FOUND: {path}")

print("\nLoading field-BG CSVs:")
for name, path in FIELD_BG_CSVS.items():
    if os.path.exists(path):
        field_bg_dfs[name] = load_test_df(path)
        print(f"  [✓] {name:<22}  {len(field_bg_dfs[name]):4d} samples")
    else:
        _missing.append(path)
        print(f"  [✗] {name:<22}  NOT FOUND: {path}")

if _missing:
    print(f"\n⚠  {len(_missing)} file(s) missing — run the Preprocessing notebook first.")
else:
    print(f"\nAll {len(lighting_dfs) + len(field_bg_dfs)} CSVs loaded OK.")

"""**Mode A - Lighting Robustness (No Segmentation)**"""

def _run_noseg(df):
    """Mode A inference on one condition DataFrame → metrics dict."""
    logits_dict, labels = collect_logits_no_seg(df, cls_models)
    preds = weighted_ensemble_probs(
        list(logits_dict.values()), best_weights_A
    ).argmax(axis=1)
    return compute_metrics(preds, labels)


_HDR = f"  {'Condition':<24}  {'Acc':>6}  {'F1':>6}  {'FPR_ND':>8}  {'ΔF1':>8}"
_SEP = "  " + "-" * 24 + "  " + "  ".join(["-" * 6, "-" * 6, "-" * 8, "-" * 8])


# ── Full test set ─────────────────────────────────────────────────────────────
print("Full test set — Mode A (No Segmentation)\n" + _HDR + "\n" + _SEP)
print(f"  {'original':<24}  "
      f"{metrics_noseg['accuracy']:6.4f}  {metrics_noseg['f1']:6.4f}  "
      f"{metrics_noseg['fpr_nutrient_def']:8.4f}  {'(baseline)':>8}")

full_lighting_mA = {}
for cond, df in lighting_dfs.items():
    m = _run_noseg(df)
    full_lighting_mA[cond] = m
    d = m["f1"] - metrics_noseg["f1"]
    print(f"  {cond:<24}  "
          f"{m['accuracy']:6.4f}  {m['f1']:6.4f}  "
          f"{m['fpr_nutrient_def']:8.4f}  {d:+8.4f}")


# ── Field-BG subset ───────────────────────────────────────────────────────────
print("\nField-BG subset — Mode A (No Segmentation)\n" + _HDR + "\n" + _SEP)

fb_lighting_mA = {}
for cond, df in field_bg_dfs.items():
    fb_lighting_mA[cond] = _run_noseg(df)

_fb_base_A = fb_lighting_mA["normal_field"]["f1"]
for cond, m in fb_lighting_mA.items():
    d      = m["f1"] - _fb_base_A if cond != "normal_field" else 0.0
    d_str  = f"{d:+8.4f}" if cond != "normal_field" else "(baseline)"
    print(f"  {cond:<24}  "
          f"{m['accuracy']:6.4f}  {m['f1']:6.4f}  "
          f"{m['fpr_nutrient_def']:8.4f}  {d_str:>8}")

"""**Mode B - Lighting Robustness (With Segmentation)**"""

def _run_seg(df):
    """Mode B inference on one condition DataFrame → metrics dict."""
    logits_dict, _, labels = collect_logits_with_seg(df, cls_models, unet_model)
    preds = weighted_ensemble_probs(
        list(logits_dict.values()), best_weights_seg
    ).argmax(axis=1)
    return compute_metrics(preds, labels)


# ── Full test set ─────────────────────────────────────────────────────────────
print("Full test set — Mode B (With Segmentation)\n" + _HDR + "\n" + _SEP)
print(f"  {'original':<24}  "
      f"{metrics_seg['accuracy']:6.4f}  {metrics_seg['f1']:6.4f}  "
      f"{metrics_seg['fpr_nutrient_def']:8.4f}  {'(baseline)':>8}")

full_lighting_mB = {}
for cond, df in lighting_dfs.items():
    print(f"\n  Running UNet inference: {cond} ...", flush=True)
    m = _run_seg(df)
    full_lighting_mB[cond] = m
    d = m["f1"] - metrics_seg["f1"]
    print(f"  {cond:<24}  "
          f"{m['accuracy']:6.4f}  {m['f1']:6.4f}  "
          f"{m['fpr_nutrient_def']:8.4f}  {d:+8.4f}")


# ── Field-BG subset ───────────────────────────────────────────────────────────
print("\n\nField-BG subset — Mode B (With Segmentation)")
print("Running UNet inference on all field-BG conditions ...", flush=True)

fb_lighting_mB = {}
for cond, df in field_bg_dfs.items():
    print(f"  {cond} ...", end=" ", flush=True)
    fb_lighting_mB[cond] = _run_seg(df)
    print("done")

_fb_base_B = fb_lighting_mB["normal_field"]["f1"]
print("\nField-BG Mode B results:\n" + _HDR + "\n" + _SEP)
for cond, m in fb_lighting_mB.items():
    d     = m["f1"] - _fb_base_B if cond != "normal_field" else 0.0
    d_str = f"{d:+8.4f}" if cond != "normal_field" else "(baseline)"
    print(f"  {cond:<24}  "
          f"{m['accuracy']:6.4f}  {m['f1']:6.4f}  "
          f"{m['fpr_nutrient_def']:8.4f}  {d_str:>8}")

"""**Summary Tables + CSV Export:**"""

_CLS_NAMES = list(CLASS_NAMES.values())              # ["Bacterial Leaf Blight", …]
_CLS_KEYS  = [cn.replace(" ", "_") for cn in _CLS_NAMES]


def _build_table(all_keys, mA_dict, mB_dict, base_key):
    """Long-form DataFrame: one row per (condition × mode) with per-class F1."""
    base_f1_A = mA_dict[base_key]["f1"]
    base_f1_B = mB_dict[base_key]["f1"]
    rows = []
    for cond in all_keys:
        for mode_lbl, m, base_f1 in [
            ("A (No Seg)",   mA_dict[cond], base_f1_A),
            ("B (With Seg)", mB_dict[cond], base_f1_B),
        ]:
            rows.append({
                "Condition": COND_DISPLAY.get(cond, cond),
                "Mode":      mode_lbl,
                "Accuracy":  round(m["accuracy"],           4),
                "F1":        round(m["f1"],                 4),
                "FPR_ND":    round(m["fpr_nutrient_def"],   4),
                "DeltaF1":   round(m["f1"] - base_f1,      4),
                **{f"F1_{k}": round(m["per_class_f1"][cn], 4)
                   for k, cn in zip(_CLS_KEYS, _CLS_NAMES)},
            })
    return pd.DataFrame(rows)


# ── Full test set table ───────────────────────────────────────────────────────
_full_order  = ["original"] + list(lighting_dfs.keys())
_full_mA_all = {"original": metrics_noseg, **full_lighting_mA}
_full_mB_all = {"original": metrics_seg,   **full_lighting_mB}

full_robustness_table = _build_table(_full_order, _full_mA_all, _full_mB_all, "original")
_disp_cols = ["Condition", "Mode", "Accuracy", "F1", "FPR_ND", "DeltaF1"]
print("Full Test Set — Lighting Robustness Summary")
print(full_robustness_table[_disp_cols].to_string(index=False))
_path = os.path.join(META_DIR, "lighting_robustness_full.csv")
full_robustness_table.to_csv(_path, index=False)
print(f"\nSaved → {_path}")

# ── Field-BG table ────────────────────────────────────────────────────────────
_fb_order = list(field_bg_dfs.keys())   # normal_field first (dict insertion order)

fb_robustness_table = _build_table(_fb_order, fb_lighting_mA, fb_lighting_mB, "normal_field")
print("\nField-BG Subset — Lighting Robustness Summary")
print(fb_robustness_table[_disp_cols].to_string(index=False))
_path = os.path.join(META_DIR, "lighting_robustness_field_bg.csv")
fb_robustness_table.to_csv(_path, index=False)
print(f"\nSaved → {_path}")

# ── Degradation rank (Mode B, full test set) ──────────────────────────────────
print("\nDegradation rank — Mode B, full test set (worst → least):")
for rank, (cond, m) in enumerate(
    sorted(full_lighting_mB.items(), key=lambda kv: kv[1]["f1"]), 1
):
    d = m["f1"] - metrics_seg["f1"]
    print(f"  {rank}. {COND_DISPLAY[cond]:<22}  F1={m['f1']:.4f}  ΔF1={d:+.4f}")

"""**Full Test Set Robustness Visualizations:**"""

_COND_ORDER_FULL  = ["original"] + list(lighting_dfs.keys())
_COND_LABELS_FULL = ["Original", "Morning\nBacklight", "Noon\nHarsh Sun",
                     "Overcast", "Low\nLight"]
_CLS_ABBREV       = ["Bacterial\nBlight", "Brown\nSpot", "Nutrient\nDef", "Healthy"]
_W = 0.35   # bar half-width

_f1_A   = np.array([_full_mA_all[c]["f1"]                for c in _COND_ORDER_FULL])
_f1_B   = np.array([_full_mB_all[c]["f1"]                for c in _COND_ORDER_FULL])
_fpr_A  = np.array([_full_mA_all[c]["fpr_nutrient_def"]  for c in _COND_ORDER_FULL])
_fpr_B  = np.array([_full_mB_all[c]["fpr_nutrient_def"]  for c in _COND_ORDER_FULL])
_dA     = _f1_A - _f1_A[0]
_dB     = _f1_B - _f1_B[0]

_x_all  = np.arange(len(_COND_ORDER_FULL))
_x_cond = np.arange(len(lighting_dfs))   # excluding original

# ── Figure 1: F1 / ΔF1 / FPR_ND bars ─────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Ensemble Robustness — Full Test Set", fontsize=14)

# F1
ax = axes[0]
ax.bar(_x_all - _W/2, _f1_A, _W, label="Mode A (No Seg)",   color="steelblue", alpha=0.85)
ax.bar(_x_all + _W/2, _f1_B, _W, label="Mode B (With Seg)", color="coral",     alpha=0.85)
for i, (a, b) in enumerate(zip(_f1_A, _f1_B)):
    ax.text(i - _W/2, a + 0.004, f"{a:.3f}", ha="center", fontsize=7.5, color="steelblue")
    ax.text(i + _W/2, b + 0.004, f"{b:.3f}", ha="center", fontsize=7.5, color="coral")
ax.set_xticks(_x_all); ax.set_xticklabels(_COND_LABELS_FULL, fontsize=9)
ax.set_ylim(max(0, min(_f1_A.min(), _f1_B.min()) - 0.10), 1.03)
ax.set_ylabel("Weighted F1"); ax.set_title("F1 Score by Condition"); ax.legend()

# ΔF1
ax = axes[1]
ax.bar(_x_cond - _W/2, _dA[1:], _W, label="Mode A", color="steelblue", alpha=0.85)
ax.bar(_x_cond + _W/2, _dB[1:], _W, label="Mode B", color="coral",     alpha=0.85)
ax.axhline(0, color="black", linewidth=0.9, linestyle="--")
for i, (a, b) in enumerate(zip(_dA[1:], _dB[1:])):
    ax.text(i - _W/2, a + (0.002 if a >= 0 else -0.007),
            f"{a:+.3f}", ha="center", fontsize=7.5, color="steelblue")
    ax.text(i + _W/2, b + (0.002 if b >= 0 else -0.007),
            f"{b:+.3f}", ha="center", fontsize=7.5, color="coral")
ax.set_xticks(_x_cond); ax.set_xticklabels(_COND_LABELS_FULL[1:], fontsize=9)
ax.set_ylabel("ΔF1 vs Original"); ax.set_title("F1 Drop per Condition"); ax.legend()

# FPR_ND
ax = axes[2]
ax.bar(_x_all - _W/2, _fpr_A, _W, label="Mode A", color="steelblue", alpha=0.85)
ax.bar(_x_all + _W/2, _fpr_B, _W, label="Mode B", color="coral",     alpha=0.85)
for i, (a, b) in enumerate(zip(_fpr_A, _fpr_B)):
    ax.text(i - _W/2, a + 0.002, f"{a:.3f}", ha="center", fontsize=7.5, color="steelblue")
    ax.text(i + _W/2, b + 0.002, f"{b:.3f}", ha="center", fontsize=7.5, color="coral")
ax.set_xticks(_x_all); ax.set_xticklabels(_COND_LABELS_FULL, fontsize=9)
ax.set_ylabel("FPR"); ax.set_title("Nutrient Def False Positive Rate"); ax.legend()

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "lighting_robustness_bars.png"), dpi=120, bbox_inches="tight")
plt.show()
print("Saved lighting_robustness_bars.png")


# ── Figure 2: Per-class F1 heatmaps (Mode A and Mode B) ──────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Per-Class F1 Across Lighting Conditions — Full Test Set", fontsize=13)

for ax, mode_lbl, m_all in [
    (axes[0], "Mode A (No Segmentation)",   _full_mA_all),
    (axes[1], "Mode B (With Segmentation)", _full_mB_all),
]:
    grid = np.array([
        [m_all[cond]["per_class_f1"][cn] for cn in _CLS_NAMES]
        for cond in _COND_ORDER_FULL
    ])
    sns.heatmap(grid, ax=ax, annot=True, fmt=".3f", cmap="RdYlGn",
                vmin=0.0, vmax=1.0, linewidths=0.4,
                xticklabels=_CLS_ABBREV, yticklabels=_COND_LABELS_FULL)
    ax.set_title(mode_lbl); ax.set_xlabel("Class"); ax.set_ylabel("Condition")

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "lighting_perclass_heatmap.png"), dpi=120, bbox_inches="tight")
plt.show()
print("Saved lighting_perclass_heatmap.png")

"""**Worst-Condition Deep Dive:**"""

_worst_cond = min(full_lighting_mB, key=lambda k: full_lighting_mB[k]["f1"])
_worst_mB   = full_lighting_mB[_worst_cond]
_worst_mA   = full_lighting_mA[_worst_cond]

print("=" * 60)
print(f"Worst lighting condition (Mode B): {COND_DISPLAY[_worst_cond]}")
print(f"  F1  = {_worst_mB['f1']:.4f}  "
      f"ΔF1 = {_worst_mB['f1'] - metrics_seg['f1']:+.4f}")
print(f"  Acc = {_worst_mB['accuracy']:.4f}  "
      f"FPR_ND = {_worst_mB['fpr_nutrient_def']:.4f}")
print("=" * 60)

# Full classification report for both modes under worst condition
print(f"\nMode A classification report — {COND_DISPLAY[_worst_cond]}:")
compute_metrics(_worst_mA["all_preds"], _worst_mA["all_labels"],
                print_report=True, print_cm=False)

print(f"\nMode B classification report — {COND_DISPLAY[_worst_cond]}:")
compute_metrics(_worst_mB["all_preds"], _worst_mB["all_labels"],
                print_report=True, print_cm=False)

# Confusion matrices: original vs worst condition (Mode B)
_short = [cn.split()[0] for cn in _CLS_NAMES]
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle(f"Mode B — Original vs Worst Condition ({COND_DISPLAY[_worst_cond]})",
             fontsize=13)

sns.heatmap(metrics_seg["confusion_matrix"], annot=True, fmt="d",
            cmap="Blues", ax=axes[0],
            xticklabels=_short, yticklabels=_short)
axes[0].set_title(f"Original  (F1 = {metrics_seg['f1']:.4f})")
axes[0].set_xlabel("Predicted"); axes[0].set_ylabel("True")

sns.heatmap(_worst_mB["confusion_matrix"], annot=True, fmt="d",
            cmap="OrRd", ax=axes[1],
            xticklabels=_short, yticklabels=_short)
axes[1].set_title(f"{COND_DISPLAY[_worst_cond]}  (F1 = {_worst_mB['f1']:.4f})")
axes[1].set_xlabel("Predicted"); axes[1].set_ylabel("True")

plt.tight_layout()
_fname = f"cm_worst_{_worst_cond}.png"
plt.savefig(os.path.join(META_DIR, _fname), dpi=120, bbox_inches="tight")
plt.show()
print(f"Saved {_fname}")

# Per-class F1 drop for the worst condition
print(f"\nPer-class F1 change under {COND_DISPLAY[_worst_cond]} (Mode B):")
for cn in _CLS_NAMES:
    orig_f1 = metrics_seg["per_class_f1"][cn]
    cond_f1 = _worst_mB["per_class_f1"][cn]
    d = cond_f1 - orig_f1
    flag = "⚠" if abs(d) > 0.05 else " "
    print(f"  {flag} {cn:<28}  original={orig_f1:.4f}  worst={cond_f1:.4f}  Δ={d:+.4f}")

"""**Field-BG Robustness Visualizations:**"""

_FB_ORDER  = list(field_bg_dfs.keys())   # ["normal_field", "morning_backlight", …]
_FB_LABELS = ["Normal\nField", "Morning\nBacklight", "Noon\nHarsh Sun",
              "Overcast", "Low\nLight"]

_f1_A_fb  = np.array([fb_lighting_mA[c]["f1"]               for c in _FB_ORDER])
_f1_B_fb  = np.array([fb_lighting_mB[c]["f1"]               for c in _FB_ORDER])
_fpr_A_fb = np.array([fb_lighting_mA[c]["fpr_nutrient_def"] for c in _FB_ORDER])
_fpr_B_fb = np.array([fb_lighting_mB[c]["fpr_nutrient_def"] for c in _FB_ORDER])
_dA_fb    = _f1_A_fb - _f1_A_fb[0]
_dB_fb    = _f1_B_fb - _f1_B_fb[0]

_x_fb   = np.arange(len(_FB_ORDER))
_x_fb_c = np.arange(len(_FB_ORDER) - 1)   # lighting conditions only

# ── Figure 3: F1 / ΔF1 / FPR_ND for field-BG ─────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Ensemble Robustness — Field-BG Subset", fontsize=14)

ax = axes[0]
ax.bar(_x_fb - _W/2, _f1_A_fb, _W, label="Mode A", color="steelblue", alpha=0.85)
ax.bar(_x_fb + _W/2, _f1_B_fb, _W, label="Mode B", color="coral",     alpha=0.85)
for i, (a, b) in enumerate(zip(_f1_A_fb, _f1_B_fb)):
    ax.text(i - _W/2, a + 0.004, f"{a:.3f}", ha="center", fontsize=7.5, color="steelblue")
    ax.text(i + _W/2, b + 0.004, f"{b:.3f}", ha="center", fontsize=7.5, color="coral")
ax.set_xticks(_x_fb); ax.set_xticklabels(_FB_LABELS, fontsize=9)
ax.set_ylim(max(0, min(_f1_A_fb.min(), _f1_B_fb.min()) - 0.10), 1.03)
ax.set_ylabel("Weighted F1"); ax.set_title("F1 Score by Condition"); ax.legend()

ax = axes[1]
ax.bar(_x_fb_c - _W/2, _dA_fb[1:], _W, label="Mode A", color="steelblue", alpha=0.85)
ax.bar(_x_fb_c + _W/2, _dB_fb[1:], _W, label="Mode B", color="coral",     alpha=0.85)
ax.axhline(0, color="black", linewidth=0.9, linestyle="--")
for i, (a, b) in enumerate(zip(_dA_fb[1:], _dB_fb[1:])):
    ax.text(i - _W/2, a + (0.002 if a >= 0 else -0.007),
            f"{a:+.3f}", ha="center", fontsize=7.5, color="steelblue")
    ax.text(i + _W/2, b + (0.002 if b >= 0 else -0.007),
            f"{b:+.3f}", ha="center", fontsize=7.5, color="coral")
ax.set_xticks(_x_fb_c); ax.set_xticklabels(_FB_LABELS[1:], fontsize=9)
ax.set_ylabel("ΔF1 vs Normal Field"); ax.set_title("F1 Drop per Condition"); ax.legend()

ax = axes[2]
ax.bar(_x_fb - _W/2, _fpr_A_fb, _W, label="Mode A", color="steelblue", alpha=0.85)
ax.bar(_x_fb + _W/2, _fpr_B_fb, _W, label="Mode B", color="coral",     alpha=0.85)
for i, (a, b) in enumerate(zip(_fpr_A_fb, _fpr_B_fb)):
    ax.text(i - _W/2, a + 0.002, f"{a:.3f}", ha="center", fontsize=7.5, color="steelblue")
    ax.text(i + _W/2, b + 0.002, f"{b:.3f}", ha="center", fontsize=7.5, color="coral")
ax.set_xticks(_x_fb); ax.set_xticklabels(_FB_LABELS, fontsize=9)
ax.set_ylabel("FPR"); ax.set_title("Nutrient Def FPR"); ax.legend()

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "lighting_robustness_field_bg.png"), dpi=120, bbox_inches="tight")
plt.show()
print("Saved lighting_robustness_field_bg.png")


# ── Figure 4: Per-class F1 heatmaps for field-BG ─────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("Per-Class F1 Across Lighting Conditions — Field-BG Subset", fontsize=13)

for ax, mode_lbl, m_dict in [
    (axes[0], "Mode A (No Segmentation)",   fb_lighting_mA),
    (axes[1], "Mode B (With Segmentation)", fb_lighting_mB),
]:
    grid = np.array([
        [m_dict[cond]["per_class_f1"][cn] for cn in _CLS_NAMES]
        for cond in _FB_ORDER
    ])
    sns.heatmap(grid, ax=ax, annot=True, fmt=".3f", cmap="RdYlGn",
                vmin=0.0, vmax=1.0, linewidths=0.4,
                xticklabels=_CLS_ABBREV, yticklabels=_FB_LABELS)
    ax.set_title(mode_lbl); ax.set_xlabel("Class"); ax.set_ylabel("Condition")

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "lighting_perclass_heatmap_field_bg.png"), dpi=120, bbox_inches="tight")
plt.show()
print("Saved lighting_perclass_heatmap_field_bg.png")


# ── Final printed summary ──────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("LIGHTING ROBUSTNESS — FINAL SUMMARY")
print("=" * 65)

best_f1_single = max(m["f1"] for m in individual_metrics_A.values())

print(f"\n{'':4}{'Condition':<22}  {'Mode A F1':>9}  {'Mode B F1':>9}  {'ΔF1 (B)':>9}")
print("  " + "-" * 55)

for cond in _COND_ORDER_FULL:
    mA = _full_mA_all[cond]
    mB = _full_mB_all[cond]
    d  = mB["f1"] - metrics_seg["f1"] if cond != "original" else 0.0
    d_str = f"{d:+.4f}" if cond != "original" else " baseline"
    print(f"  {COND_DISPLAY[cond]:<22}  "
          f"{mA['f1']:9.4f}  {mB['f1']:9.4f}  {d_str:>9}")

print(f"\n  Saved CSVs:")
print(f"    lighting_robustness_full.csv")
print(f"    lighting_robustness_field_bg.csv")
print(f"\n  Saved figures:")
print(f"    lighting_robustness_bars.png")
print(f"    lighting_perclass_heatmap.png")
print(f"    cm_worst_{_worst_cond}.png")
print(f"    lighting_robustness_field_bg.png")
print(f"    lighting_perclass_heatmap_field_bg.png")
print("=" * 65)

"""**Save Final Results CSV:**"""

final_results = {
    "Method": list(individual_metrics_A.keys()) + ["Ensemble-A (No Segmentation)", "Ensemble-B (With Segmentation)"],
    "Accuracy": [m["accuracy"] for m in individual_metrics_A.values()] + [metrics_noseg["accuracy"], metrics_seg["accuracy"]],
    "F1": [m["f1"] for m in individual_metrics_A.values()] + [metrics_noseg["f1"], metrics_seg["f1"]],
    "FPR_NutrientDef": [m["fpr_nutrient_def"] for m in individual_metrics_A.values()] + [metrics_noseg["fpr_nutrient_def"], metrics_seg["fpr_nutrient_def"]],
}
final_df = pd.DataFrame(final_results).round(4)
print(final_df.to_string(index=False))

out_path = os.path.join(META_DIR, "thesis_final_results.csv")
final_df.to_csv(out_path, index=False)
print(f"\nSaved -> {out_path}")

"""**Single-Image Demo — Segmentation + Ensemble Prediction:**

Picks one random test image, runs the UNet, visualises the mask, runs the Mode B (segmentation) ensemble on it with the weights selected in Section 17, and prints the verdict against ground truth. Re-run the cell below for a different random sample.
"""

SEG_COLORS = {0: [0, 0, 0], 1: [255, 0, 0], 2: [255, 165, 0], 3: [0, 200, 0]}
SEG_LEGEND = {1: "Bacterial (red)", 2: "Brown spot (orange)", 3: "Nutrient def (green)", 0: "Background (black)"}

def seg_inference_single(unet, image_rgb_512, tta=SEG_TTA):
    def _fwd(img_np):
        aug = seg_transform(image=img_np)
        x = aug["image"].unsqueeze(0).to(DEVICE)
        with torch.no_grad(), torch.amp.autocast("cuda"):
            logit = unet(x)
        return torch.softmax(logit.squeeze(0), dim=0)

    probs = _fwd(image_rgb_512)
    if tta:
        hf = _fwd(np.fliplr(image_rgb_512).copy())
        probs = probs + torch.flip(hf, [2])
        vf = _fwd(np.flipud(image_rgb_512).copy())
        probs = probs + torch.flip(vf, [1])
        probs = probs / 3.0
    return probs.cpu()

def run_ensemble_demo(df, unet, classifiers, ensemble_weights, sample_idx=None):
    sample_idx = sample_idx if sample_idx is not None else random.randint(0, len(df) - 1)
    sample = df.iloc[sample_idx]
    img_path, true_label = sample["image_path"], int(sample["label"])

    image_bgr = cv2.imread(img_path)
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    image_512 = cv2.resize(image_rgb, (IMG_SIZE_SEG, IMG_SIZE_SEG))

    unet.eval()
    seg_probs = seg_inference_single(unet, image_512)

    fg_prob = 1.0 - seg_probs[0].numpy()
    weight_map = ((1.0 - SEG_ALPHA) + SEG_ALPHA * fg_prob)[:, :, np.newaxis]
    masked_512 = (image_512.astype(np.float32) * weight_map).clip(0, 255).astype(np.uint8)
    masked_display = cv2.resize(masked_512, (image_rgb.shape[1], image_rgb.shape[0]))

    seg_argmax = seg_probs.argmax(dim=0).numpy()
    seg_vis = np.zeros((512, 512, 3), dtype=np.uint8)
    for cls_idx, color in SEG_COLORS.items():
        seg_vis[seg_argmax == cls_idx] = color

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(image_rgb); axes[0].set_title("Original image"); axes[0].axis("off")
    axes[1].imshow(seg_vis); axes[1].set_title("UNet segmentation mask"); axes[1].axis("off")
    axes[2].imshow(masked_display); axes[2].set_title("Masked image (classifier input)"); axes[2].axis("off")
    fig.text(0.5, -0.02, "\n".join(SEG_LEGEND.values()), ha="center", fontsize=9, color="gray")
    plt.tight_layout(); plt.show()

    per_pixel_class = seg_argmax.flatten()
    pixel_counts = np.bincount(per_pixel_class, minlength=SEG_NUM_CLASSES)
    seg_to_cls = [3, 0, 1, 2]
    seg_prior = np.zeros(NUM_CLASSES, dtype=np.float32)
    for seg_idx, cls_idx in enumerate(seg_to_cls):
        seg_prior[cls_idx] = pixel_counts[seg_idx]
    seg_prior /= seg_prior.sum() + 1e-8

    input_tensor = val_transform(masked_512).unsqueeze(0).to(DEVICE)
    all_probs = []
    with torch.no_grad():
        for model in classifiers:
            logits = model(input_tensor)
            all_probs.append(torch.softmax(logits, dim=1).cpu().numpy()[0])

    ensemble_probs = np.zeros(NUM_CLASSES)
    for w, probs in zip(ensemble_weights, all_probs):
        ensemble_probs += w * probs
    pred_class = int(np.argmax(ensemble_probs))

    print("=" * 60)
    print("SEGMENTATION + ENSEMBLE PREDICTION")
    print("=" * 60)
    print(f"\nImage: {img_path}")
    print("\nUNet seg prior (mapped to classifier classes):")
    for i, name in CLASS_NAMES.items():
        print(f"  {name:<25}: {seg_prior[i]*100:.1f}%")
    print(f"\nPredicted Disease : {CLASS_NAMES[pred_class]}")
    print(f"Overall Confidence: {ensemble_probs[pred_class]*100:.2f}%")
    print("\nClass Probabilities (weighted ensemble):")
    for class_idx, class_name in CLASS_NAMES.items():
        bar = "#" * int(ensemble_probs[class_idx] * 30)
        print(f"  {class_name:<25}: {ensemble_probs[class_idx]*100:6.2f}%  {bar}")
    print(f"\nGround Truth: {CLASS_NAMES[true_label]}")
    print("\nResult:", "CORRECT" if pred_class == true_label else "INCORRECT")
    print("=" * 60)
    return pred_class, true_label

# Run one demo. Re-run this cell for a new random sample.
_ = run_ensemble_demo(test_df, unet_model, [mobilenet_model, nasnet_model, effnet_model], best_weights_seg)