# -*- coding: utf-8 -*-
"""Preprocessing (Final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvLvCLZcQ67Wg-yloWE84Ar3hzgnZ_sY

# **Preprocessing**

**Prerequisites:**
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

"""**Paths:**"""

PROJECT_ROOT = "/content/drive/MyDrive/thesis"

RAW_DIR      = os.path.join(PROJECT_ROOT, "data/raw")
MASK_DIR     = os.path.join(PROJECT_ROOT, "data/raw/masks")
HEALTHY_DIR  = os.path.join(PROJECT_ROOT, "data/raw/healthy")
AUG_DIR      = os.path.join(PROJECT_ROOT, "data/augmented")
META_DIR     = os.path.join(PROJECT_ROOT, "data/metadata")

os.makedirs(META_DIR, exist_ok=True)
os.makedirs(AUG_DIR,  exist_ok=True)

"""**Configuration:**"""

IMG_SIZE     = 512
RANDOM_STATE = 42
IMG_EXTS     = {".jpg", ".jpeg", ".png"}

print("RAW_DIR    :", RAW_DIR)
print("MASK_DIR   :", MASK_DIR)
print("HEALTHY_DIR:", HEALTHY_DIR)
print("AUG_DIR    :", AUG_DIR)
print("META_DIR   :", META_DIR)

"""**Class Definitions:**"""

CLASSES = [
    {
        "class_id": 1,
        "name": "bacterial_leaf_blight",
        "subfolders": ["field_bg", "white_bg"]
    },
    {
        "class_id": 2,
        "name": "brown_spot",
        "subfolders": ["field_bg", "white_bg"]
    },
    {
        "class_id": 3,
        "name": "nutrient_deficiency",
        "subfolders": ["phosphorus", "potassium"]
    },
]

NUM_CLASSES = len(CLASSES) + 1 + 1  # +1 background, +1 healthy
CLASS_MAP   = {c["name"]: c["class_id"] for c in CLASSES}
CLASS_MAP["healthy"] = 4

print("CLASS_MAP   :", CLASS_MAP)
print("NUM_CLASSES :", NUM_CLASSES)

"""**Helper Functions:**

**Image:** bacterial_leaf_blight_field_bg_1

**Mask:** bacterial_leaf_blight_field_bg_mask_1
"""

def build_mask_stem(img_stem):
    parts = img_stem.rsplit("_", 1)
    if len(parts) != 2 or not parts[1].isdigit():
        print(f"Unexpected filename (skipped): {img_stem}")
        return None
    base, idx = parts
    return f"{base}_mask_{idx}"


def find_mask_file(mask_dir, mask_stem):
    for ext in [".png", ".jpg", ".jpeg"]:
        p = Path(mask_dir) / f"{mask_stem}{ext}"
        if p.exists():
            return str(p)
    return None

"""Validates that:

*   Both files are readable
*   Mask is non-empty
"""

def validate_pair(img_path, mask_path):
    img = cv2.imread(img_path)
    if img is None:
        return False, "unreadable_image"

    mask = cv2.imread(mask_path, 0)
    if mask is None:
        return False, "unreadable_mask"

    if mask.max() == 0:
        return False, "empty_mask"

    if mask.shape[0] < 32 or mask.shape[1] < 32:
        return False, f"mask_too_small_{mask.shape}"

    return True, "ok"

"""Validation for classes with no masks (healthy)"""

def validate_image_only(img_path):
    img = cv2.imread(img_path)
    if img is None:
        return False, "unreadable_image"
    if img.shape[0] < 32 or img.shape[1] < 32:
        return False, f"image_too_small_{img.shape}"
    return True, "ok"

"""**Scan Dataset:**"""

print("Pre-loading Drive directory cache...")
try:
    _ = os.listdir(RAW_DIR)
    _ = os.listdir(MASK_DIR)
    for cls in CLASSES:
        cls_img_dir  = os.path.join(RAW_DIR,  cls["name"])
        cls_mask_dir = os.path.join(MASK_DIR, cls["name"])
        if os.path.exists(cls_img_dir):
            _ = os.listdir(cls_img_dir)
        if os.path.exists(cls_mask_dir):
            _ = os.listdir(cls_mask_dir)
except Exception as e:
    print(f"Cache preload warning: {e}")
print("Cache ready — starting scan\n")

records         = []
total_scanned   = 0
skipped_naming  = 0
skipped_no_mask = 0
skipped_bad     = 0

for cls in CLASSES:
    class_id       = cls["class_id"]
    class_name     = cls["name"]
    class_img_dir  = os.path.join(RAW_DIR,  class_name)
    class_mask_dir = os.path.join(MASK_DIR, class_name)

    print(f"\nScanning: {class_name}")

    if not os.path.exists(class_img_dir):
        print(f"Missing image directory: {class_img_dir}")
        continue
    if not os.path.exists(class_mask_dir):
        print(f"Missing mask directory:  {class_mask_dir}")
        continue

    for root, dirs, files in os.walk(class_img_dir):
        dirs.sort()

        rel_subdir = os.path.relpath(root, class_img_dir)

        mask_subdir = os.path.join(class_mask_dir, rel_subdir)

        subfolder_count = 0

        for fname in sorted(files):
            img_path = os.path.join(root, fname)

            if Path(img_path).suffix.lower() not in IMG_EXTS:
                continue
            total_scanned += 1

            img_stem = Path(img_path).stem

            mask_stem = build_mask_stem(img_stem)
            if mask_stem is None:
                skipped_naming += 1
                continue

            mask_path = find_mask_file(mask_subdir, mask_stem)
            if mask_path is None:
                skipped_no_mask += 1
                continue

            valid, reason = validate_pair(img_path, mask_path)
            if not valid:
                print(f"Skipped {fname}: {reason}")
                skipped_bad += 1
                continue

            records.append({
                "image_path": img_path,
                "mask_path":  mask_path,
                "class_name": class_name,
                "class_id":   class_id,
                "subfolder":  rel_subdir,
                "augmented":  False,
            })
            subfolder_count += 1

        if subfolder_count > 0 or os.path.exists(mask_subdir):
            print(f"  [{rel_subdir}] → {subfolder_count} valid pairs")

print(f"\nDisease classes scanned — {len(records)} valid pairs so far")

print(f"\nScanning: healthy")

healthy_count   = 0
healthy_skipped = 0

if not os.path.exists(HEALTHY_DIR):
    print(f"Missing healthy directory: {HEALTHY_DIR}")
else:
    for fname in sorted(os.listdir(HEALTHY_DIR)):
        img_path = os.path.join(HEALTHY_DIR, fname)

        if Path(img_path).suffix.lower() not in IMG_EXTS:
            continue
        total_scanned += 1

        valid, reason = validate_image_only(img_path)
        if not valid:
            print(f"Skipped {fname}: {reason}")
            healthy_skipped += 1
            skipped_bad += 1
            continue

        records.append({
            "image_path": img_path,
            "mask_path":  "",       # no mask for healthy
            "class_name": "healthy",
            "class_id":   4,
            "subfolder":  ".",
            "augmented":  False,
        })
        healthy_count += 1

    print(f"  [flat] → {healthy_count} valid images  "
          f"({healthy_skipped} skipped)")

df = pd.DataFrame(records)

print("\n" + "="*50)
print(f"  Total images scanned  : {total_scanned}")
print(f"  Valid records         : {len(df)}")
print(f"  Skipped (naming)      : {skipped_naming}")
print(f"  Skipped (no mask)     : {skipped_no_mask}")
print(f"  Skipped (bad)         : {skipped_bad}")
print("="*50)

if len(df) > 0:
    print("\nPer-class breakdown:")
    print(df["class_name"].value_counts())
else:
    print("No valid records found — check directory paths and naming convention.")

"""**Sanity Check:**

Checks class id integrity
"""

print("class_id → class_name mapping:")
print(df.groupby(["class_id", "class_name"]).size().reset_index(name="count"))

assert df["class_id"].isna().sum()   == 0, "NaN class_ids found!"
assert df["image_path"].isna().sum() == 0, "NaN image_paths found!"
assert df["mask_path"].isna().sum()  == 0, "NaN mask_paths found!"
assert set(df["class_id"].unique()).issubset({1, 2, 3, 4}), "Unexpected class_id values!"

print("\nAll checks passed — data looks clean")

"""**Dataset Statistics (Before Augmentation):**"""

fig, ax = plt.subplots(figsize=(8, 4))
df["class_name"].value_counts().plot(
    kind="bar", ax=ax,
    color=["steelblue", "darkorange", "green", "mediumpurple"])
plt.title("Class Distribution (before augmentation)")
plt.ylabel("Samples")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "class_distribution_before_aug.png"), dpi=100)
plt.show()
print("Saved class_distribution_before_aug.png")

"""**Augmentation:**

**Augmentation target** = 750

**Transforms Applied:**

1. Horizontal flip
2. Small rotation ±10°
3. Brightness / Contrast jitter ±15 %
4. Gentle Gaussian blur kernel 3×3
"""

AUG_TARGET   = 750
AUG_SEED     = RANDOM_STATE

rng = np.random.default_rng(AUG_SEED)

def aug_hflip(img, mask=None):
    img_out = cv2.flip(img, 1)
    mask_out = cv2.flip(mask, 1) if mask is not None else None
    return img_out, mask_out

def aug_rotate(img, mask=None, angle_deg=8):
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w / 2, h / 2), angle_deg, 1.0)
    img_out  = cv2.warpAffine(img,  M, (w, h), flags=cv2.INTER_LINEAR,
                               borderMode=cv2.BORDER_REFLECT_101)
    if mask is not None:
        mask_out = cv2.warpAffine(mask, M, (w, h), flags=cv2.INTER_NEAREST,
                                  borderMode=cv2.BORDER_REFLECT_101)
    else:
        mask_out = None
    return img_out, mask_out

def aug_brightness(img, mask=None, alpha=1.12, beta=10):
    img_out  = np.clip(img.astype(np.float32) * alpha + beta, 0, 255).astype(np.uint8)
    mask_out = mask
    return img_out, mask_out

def aug_blur(img, mask=None):
    img_out  = cv2.GaussianBlur(img, (3, 3), 0)
    mask_out = mask
    return img_out, mask_out

TRANSFORMS = {
    "hflip":      (aug_hflip,       {}),
    "rotate_cw":  (aug_rotate,      {"angle_deg":  8}),
    "rotate_ccw": (aug_rotate,      {"angle_deg": -8}),
    "brightness": (aug_brightness,  {"alpha": 1.12, "beta":  10}),
    "dim":        (aug_brightness,  {"alpha": 0.88, "beta": -10}),
    "blur":       (aug_blur,        {}),
}

aug_records = []

counts = df["class_name"].value_counts().to_dict()

for class_name, current_count in sorted(counts.items()):
    needed = AUG_TARGET - current_count
    if needed <= 0:
        print(f"  ⏭️  {class_name}: {current_count} samples — at/above target, skipping")
        continue

    print(f"\nAugmenting {class_name}: {current_count} → {AUG_TARGET}  (+{needed})")

    class_aug_dir      = os.path.join(AUG_DIR, class_name)
    class_aug_mask_dir = os.path.join(AUG_DIR, class_name, "masks")
    os.makedirs(class_aug_dir,      exist_ok=True)
    os.makedirs(class_aug_mask_dir, exist_ok=True)

    cls_rows = df[df["class_name"] == class_name].reset_index(drop=True)
    class_id = int(cls_rows["class_id"].iloc[0])

    transform_names = list(TRANSFORMS.keys())
    generated = 0

    for t_idx, t_name in enumerate(
        [transform_names[i % len(transform_names)] for i in range(needed)]
    ):
        src_row = cls_rows.iloc[t_idx % len(cls_rows)]

        img = cv2.imread(src_row["image_path"])
        if img is None:
            continue

        mask = None
        if src_row["mask_path"]:
            mask = cv2.imread(src_row["mask_path"], 0)

        fn, kwargs = TRANSFORMS[t_name]
        aug_img, aug_mask = fn(img, mask, **kwargs)

        src_stem = Path(src_row["image_path"]).stem
        aug_img_fname  = f"aug_{t_name}_{src_stem}.jpg"
        aug_img_path   = os.path.join(class_aug_dir, aug_img_fname)
        cv2.imwrite(aug_img_path, aug_img, [cv2.IMWRITE_JPEG_QUALITY, 95])

        aug_mask_path = ""
        if aug_mask is not None:
            aug_mask_fname = f"aug_{t_name}_{src_stem}_mask.png"
            aug_mask_path  = os.path.join(class_aug_mask_dir, aug_mask_fname)
            cv2.imwrite(aug_mask_path, aug_mask)

        aug_records.append({
            "image_path": aug_img_path,
            "mask_path":  aug_mask_path,
            "class_name": class_name,
            "class_id":   class_id,
            "subfolder":  "augmented",
            "augmented":  True,
        })
        generated += 1

    print(f"Generated {generated} augmented images → {class_aug_dir}")

aug_df = pd.DataFrame(aug_records)
df     = pd.concat([df, aug_df], ignore_index=True)

print("\n" + "="*50)
print("Post-augmentation class distribution:")
print(df["class_name"].value_counts())
print(f"\nTotal records (raw + augmented): {len(df)}")
print("="*50)

"""**Dataset Statistics (After Augmentation):**"""

fig, ax = plt.subplots(figsize=(8, 4))
df["class_name"].value_counts().plot(
    kind="bar", ax=ax,
    color=["steelblue", "darkorange", "green", "mediumpurple"])
plt.title("Class Distribution (after augmentation)")
plt.ylabel("Samples")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "class_distribution_after_aug.png"), dpi=100)
plt.show()
print("Saved class_distribution_after_aug.png")

"""**Visualize Sample Image-Mask Pairs:**"""

ALL_CLASSES = CLASSES + [{"class_id": 4, "name": "healthy", "subfolders": []}]

originals_df = df[df["augmented"] == False]

fig, axes = plt.subplots(4, 4, figsize=(14, 13))
fig.suptitle("Sample Image–Mask Pairs (2 per class, originals only)", fontsize=14)

for cls_idx, cls in enumerate(ALL_CLASSES):
    subset = originals_df[originals_df["class_id"] == cls["class_id"]].sample(
        min(2, (originals_df["class_id"] == cls["class_id"]).sum()),
        random_state=RANDOM_STATE
    ).reset_index(drop=True)

    for i, row in subset.iterrows():
        img = cv2.cvtColor(cv2.imread(row["image_path"]), cv2.COLOR_BGR2RGB)

        axes[cls_idx][i * 2].imshow(img)
        axes[cls_idx][i * 2].set_title(f"{cls['name']}\n(image)", fontsize=8)
        axes[cls_idx][i * 2].axis("off")

        if row["mask_path"]:
            mask = cv2.imread(row["mask_path"], 0)
            axes[cls_idx][i * 2 + 1].imshow(mask, cmap="gray")
            axes[cls_idx][i * 2 + 1].set_title(f"{cls['name']}\n(mask)", fontsize=8)
        else:
            axes[cls_idx][i * 2 + 1].imshow(img)
            axes[cls_idx][i * 2 + 1].set_title(f"{cls['name']}\n(no mask)", fontsize=8)
        axes[cls_idx][i * 2 + 1].axis("off")

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "sample_pairs.png"), dpi=100)
plt.show()
print("Saved sample_pairs.png")

"""**Train / Test Split:**"""

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["class_id"],
    random_state=RANDOM_STATE,
    shuffle=True
)

train_df = train_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

print(f"Train : {len(train_df)}")
print(f"Test  : {len(test_df)}")
print("\nTrain class distribution:")
print(train_df["class_name"].value_counts())
print("\nTest class distribution:")
print(test_df["class_name"].value_counts())

"""**Separate Field Background Test Set:**"""

test_field_bg_df = test_df[
    (
        (test_df["class_name"] == "bacterial_leaf_blight") &
        (test_df["subfolder"].isin(["field_bg", "augmented"]))
    )
    |
    (
        (test_df["class_name"] == "brown_spot") &
        (test_df["subfolder"].isin(["field_bg", "augmented"]))
    )
    |
    (
        test_df["class_name"] == "nutrient_deficiency"
    )
    |
    (
        test_df["class_name"] == "healthy"
    )
].copy()

test_field_bg_df = test_field_bg_df.reset_index(drop=True)

print("\nField BG Test Distribution:")
print(test_field_bg_df["class_name"].value_counts())
print(f"Field BG Test Samples: {len(test_field_bg_df)}")

"""**Save CSV Files:**"""

TRAIN_CSV         = os.path.join(META_DIR, "train.csv")
TEST_CSV          = os.path.join(META_DIR, "test.csv")
TEST_FIELD_BG_CSV = os.path.join(META_DIR, "test_field_bg.csv")

train_df.to_csv(TRAIN_CSV,         index=False)
test_df.to_csv(TEST_CSV,           index=False)
test_field_bg_df.to_csv(TEST_FIELD_BG_CSV, index=False)

print(f"Saved: {TRAIN_CSV}")
print(f"Saved: {TEST_CSV}")
print(f"Saved: {TEST_FIELD_BG_CSV}")
print("\nColumn schema:")
print(train_df.dtypes)
print("\nSample rows:")
print(train_df.head(3))