# -*- coding: utf-8 -*-
"""Segmentation (Final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcEoXTaVBjaAO1FkvI8rp2EFwzzcZMal

# **Segmentation**
"""

!pip install segmentation-models-pytorch albumentations timm --quiet

"""**Prerequisites:**"""

from google.colab import drive
drive.mount('/content/drive')

import gc
import os
import math
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import albumentations as A
from albumentations.pytorch import ToTensorV2

import segmentation_models_pytorch as smp
from sklearn.model_selection import train_test_split
from tqdm import tqdm

gc.collect()
torch.cuda.empty_cache()
print('Imports OK')

"""**Configuration:**"""

PROJECT_ROOT = "/content/drive/MyDrive/thesis"

TRAIN_CSV = "/content/drive/MyDrive/thesis/data/metadata/train.csv"
TEST_CSV  = "/content/drive/MyDrive/thesis/data/metadata/test.csv"

MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
META_DIR   = os.path.join(PROJECT_ROOT, "data/metadata")

SAVE_PATH  = os.path.join(MODELS_DIR, "best_unet_b5_scse_v10.pth")

for _d in [PROJECT_ROOT, os.path.dirname(TRAIN_CSV)]:
    try:
        _ = os.listdir(_d)
    except Exception:
        pass

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(META_DIR,   exist_ok=True)

IMG_SIZE          = 512
BATCH_SIZE        = 4
ACCUM_STEPS       = 4
NUM_CLASSES       = 4
EPOCHS            = 100
LR                = 2e-4
WARMUP_EPOCHS     = 10
PATIENCE          = 40
RANDOM_STATE      = 42
SWA_START         = 50
TTA_VAL_START     = 20
MASK_THRESHOLD    = 127   # ← was 200; standard binary midpoint recovers more annotation area
BS_MASK_THRESHOLD = 100   # ← NEW: Brown Spot gets lower threshold — soft lesion borders
                           #        and JPEG compression erase the outer ring at 200

CLASS_NAMES = {
    1: "Bacterial Leaf Blight",
    2: "Brown Spot",
    3: "Nutrient Deficiency"
}

DISEASE_CLASS_IDS = {1, 2, 3}

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)
print(f"Effective batch size: {BATCH_SIZE * ACCUM_STEPS}")
print(f"LR: decoder/head={LR:.1e}  encoder={LR/10:.1e}")
print(f"Mask threshold (default)    : {MASK_THRESHOLD}")
print(f"Mask threshold (Brown Spot) : {BS_MASK_THRESHOLD}")

"""**Load CSV:**"""

df_train_full = pd.read_csv(TRAIN_CSV)
df_test       = pd.read_csv(TEST_CSV)

assert "class_id" in df_train_full.columns, \
    "class_id missing — re-run Notebook 1"
assert df_train_full["class_id"].isna().sum() == 0, \
    "NaN class_ids found in train.csv"

df_train_full = df_train_full[df_train_full["class_id"].isin(DISEASE_CLASS_IDS)].reset_index(drop=True)
df_test       = df_test[df_test["class_id"].isin(DISEASE_CLASS_IDS)].reset_index(drop=True)

print(f"Train rows after healthy filter : {len(df_train_full)}")
print(f"Test rows after healthy filter  : {len(df_test)}")
print("\nTrain class distribution (disease only):")
print(df_train_full["class_name"].value_counts())
print("\nTest class distribution (disease only):")
print(df_test["class_name"].value_counts())

# **Train / Val Split:**

train_df, val_df = train_test_split(
    df_train_full,
    test_size=0.2,
    stratify=df_train_full["class_id"],
    random_state=RANDOM_STATE
)

train_df = train_df.reset_index(drop=True)
val_df   = val_df.reset_index(drop=True)

print(f"Train : {len(train_df)}")
print(f"Val   : {len(val_df)}")
print(f"Test  : {len(df_test)}")

"""**CSV Integrity Validation:**"""

OLD_ROOT = "/content/drive/MyDrive/Thesis Model"
NEW_ROOT = "/content/drive/MyDrive/thesis"

def repair_paths(df):
    df = df.copy()
    df["image_path"] = df["image_path"].str.replace(OLD_ROOT, NEW_ROOT, regex=False)
    df["mask_path"]  = df["mask_path"].str.replace(OLD_ROOT, NEW_ROOT, regex=False)
    return df

train_df = repair_paths(train_df)
val_df   = repair_paths(val_df)
df_test  = repair_paths(df_test)

def validate_dataframe(df, name):
    missing_images = []
    missing_masks  = []

    for _, row in df.iterrows():
        if not os.path.exists(row["image_path"]):
            missing_images.append(row["image_path"])
        if not os.path.exists(row["mask_path"]):
            missing_masks.append(row["mask_path"])

    print(f"\n{name}")
    print(f"  Rows          : {len(df)}")
    print(f"  Missing images: {len(missing_images)}")
    print(f"  Missing masks : {len(missing_masks)}")

    if missing_images:
        print(f"\n  Example missing image:\n  {missing_images[0]}")
    if missing_masks:
        print(f"\n  Example missing mask:\n  {missing_masks[0]}")

    assert len(missing_images) == 0, "❌ Missing image files"
    assert len(missing_masks)  == 0, "❌ Missing mask files"

validate_dataframe(train_df, "TRAIN")
validate_dataframe(val_df,   "VAL")
validate_dataframe(df_test,  "TEST")

print("\nCSV integrity verified — all image and mask files found")
print(f"Augmented rows in train : {train_df['augmented'].sum()}")
print(f"Original rows in train  : {(~train_df['augmented']).sum()}")

"""**Augmentation Transforms:**

This is to help with overfitting. It ensures the model never sees the exact same pixel arrangement, even for the augmented copies.
"""

train_transform = A.Compose([
    A.RandomResizedCrop(
        size=(IMG_SIZE, IMG_SIZE),
        scale=(0.7, 1.0),
        ratio=(0.75, 1.33),
        p=0.5
    ),
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.ShiftScaleRotate(
        shift_limit=0.1,
        scale_limit=0.2,
        rotate_limit=30,
        border_mode=cv2.BORDER_REFLECT_101,
        p=0.6
    ),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.ElasticTransform(alpha=1.0, sigma=50, p=0.25),
    A.GridDistortion(num_steps=5, distort_limit=0.2, p=0.2),
    A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3, p=0.5),
    A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.4),
    A.RandomGamma(gamma_limit=(70, 130), p=0.3),
    A.CLAHE(clip_limit=4.0, tile_grid_size=(8, 8), p=0.3),
    A.GaussianBlur(blur_limit=(3, 7), p=0.2),
    A.Sharpen(alpha=(0.2, 0.5), lightness=(0.5, 1.0), p=0.2),
    A.CoarseDropout(
        num_holes_range=(1, 6),
        hole_height_range=(10, 40),
        hole_width_range=(10, 40),
        p=0.25
    ),
    A.Normalize(),
    ToTensorV2()
])

# Brown Spot: gentler geometric transforms to preserve small circular lesions,
# stronger colour augmentation to learn spot appearance variation.
# Key changes vs old version:
#   - scale=(0.75, 1.0)     was (0.5, 0.9)  — stops cropping lesions out of frame
#   - rotate_limit=20        was 45          — less likely to push spots off-edge
#   - ElasticTransform OFF                   — alpha=2.0 was warping spots into noise
#   - GridDistortion OFF                     — same reason
#   - Sharpen alpha=(0.2,0.4) was (0.4,0.8) — over-sharpening created false edges
#   - CoarseDropout OFF                      — was punching holes through small lesions
#   - Stronger colour/contrast augmentation stays — spots vary a lot in appearance
brown_spot_transform = A.Compose([
    A.RandomResizedCrop(
        size=(IMG_SIZE, IMG_SIZE),
        scale=(0.75, 1.0),      # ← was (0.5, 0.9): conservative — keep lesions visible
        ratio=(0.9, 1.1),       # ← was (0.75, 1.33): near-square, spots are circular
        p=0.4                   # ← was 0.6: apply less often
    ),
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.ShiftScaleRotate(
        shift_limit=0.05,       # ← was 0.1: smaller shift keeps spots centred
        scale_limit=0.1,        # ← was 0.2
        rotate_limit=20,        # ← was 45: mild rotation only
        border_mode=cv2.BORDER_REFLECT_101,
        p=0.5                   # ← was 0.7
    ),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    # ElasticTransform removed — alpha=2.0 was warping small circular spots into noise
    # GridDistortion removed  — same reason; these two destroyed lesion shape
    A.RandomBrightnessContrast(brightness_limit=0.35, contrast_limit=0.35, p=0.6),
    A.HueSaturationValue(hue_shift_limit=15, sat_shift_limit=30, val_shift_limit=20, p=0.5),
    A.RandomGamma(gamma_limit=(75, 125), p=0.3),
    A.CLAHE(clip_limit=3.5, tile_grid_size=(8, 8), p=0.4),
    A.GaussianBlur(blur_limit=(3, 5), p=0.15),
    A.Sharpen(alpha=(0.2, 0.4), lightness=(0.8, 1.0), p=0.3),  # ← was (0.4,0.8): gentler
    # CoarseDropout removed — was punching holes through lesions smaller than the holes
    A.Normalize(),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(),
    ToTensorV2()
])

print(f"Train transforms     : {len(train_transform.transforms)}")
print(f"BrownSpot transforms : {len(brown_spot_transform.transforms)}")
print("Augmentations ready")

"""**Dataset:**"""

class SegmentationDataset(Dataset):

    def __init__(self, df, transform=None, brown_spot_transform=None, img_size=512):
        self.df                   = df.reset_index(drop=True)
        self.transform            = transform
        self.brown_spot_transform = brown_spot_transform
        self.img_size             = img_size
        self._warned              = set()

    def __len__(self):
        return len(self.df)

    def _make_zeros(self):
        img  = torch.zeros(3, self.img_size, self.img_size, dtype=torch.float32)
        mask = torch.zeros(self.img_size, self.img_size, dtype=torch.long)
        return img, mask

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        image = cv2.imread(row["image_path"])
        if image is None:
            if row["image_path"] not in self._warned:
                print(f"\nCannot read image: {row['image_path']}")
                self._warned.add(row["image_path"])
            return self._make_zeros()

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        mask = cv2.imread(row["mask_path"], 0)
        if mask is None:
            if row["mask_path"] not in self._warned:
                print(f"\nCannot read mask : {row['mask_path']}")
                self._warned.add(row["mask_path"])
            return self._make_zeros()

        image = cv2.resize(image, (self.img_size, self.img_size))
        mask  = cv2.resize(mask,  (self.img_size, self.img_size),
                           interpolation=cv2.INTER_NEAREST)

        class_id = int(row["class_id"])
        # ← UPDATED: class-conditional threshold
        # Brown Spot lesion borders are soft and JPEG-compressed masks lose
        # the outer ring at threshold=200; lower threshold recovers those pixels.
        thresh = BS_MASK_THRESHOLD if class_id == 2 else MASK_THRESHOLD
        mask   = (mask >= thresh).astype(np.uint8)
        mask   = np.where(mask == 1, class_id, 0).astype(np.uint8)

        # Use gentler augmentation for Brown Spot
        is_brown_spot = (class_id == 2)
        tfm = (
            self.brown_spot_transform
            if is_brown_spot and self.brown_spot_transform
            else self.transform
        )

        if tfm:
            transformed = tfm(image=image, mask=mask)
            image = transformed["image"]
            mask  = transformed["mask"]

        return image, mask.long()

"""**Class Weights:**"""

def compute_class_weights(df, num_classes=4, img_size=512, n_sample=200):
    counts  = np.zeros(num_classes, dtype=np.float64)
    skipped = 0

    originals = df[df["augmented"] == False]
    pool      = originals if len(originals) >= n_sample else df

    sample = pool.sample(min(n_sample, len(pool)), random_state=RANDOM_STATE)

    for _, row in tqdm(sample.iterrows(), total=len(sample),
                       desc="Computing class weights"):
        if not os.path.exists(row["mask_path"]):
            skipped += 1
            continue

        mask = cv2.imread(row["mask_path"], 0)
        if mask is None:
            skipped += 1
            continue

        mask     = cv2.resize(mask, (img_size, img_size),
                              interpolation=cv2.INTER_NEAREST)
        # ← UPDATED: class-conditional threshold to match SegmentationDataset exactly
        class_id = int(row["class_id"])
        thresh   = BS_MASK_THRESHOLD if class_id == 2 else MASK_THRESHOLD
        mask     = (mask >= thresh).astype(np.uint8)
        mask     = np.where(mask == 1, class_id, 0)

        for c in range(num_classes):
            counts[c] += (mask == c).sum()

    if skipped > 0:
        print(f"Skipped {skipped}/{len(sample)} masks (unreadable)")

    if counts.sum() == 0:
        print("No masks read — using uniform weights")
        return torch.ones(num_classes, dtype=torch.float32).to(DEVICE)

    weights = 1.0 / (counts + 1)
    weights = weights / weights.sum() * num_classes

    labels = ["background", "bacterial", "brown_spot", "nutrient"]
    print("\nPixel counts & weights:")
    for c, (cnt, w) in enumerate(zip(counts, weights)):
        print(f"  [{c}] {labels[c]:12s}: {int(cnt):>12,} px  weight={w:.4f}")

    return torch.tensor(weights, dtype=torch.float32).to(DEVICE)


class_weights = compute_class_weights(train_df, NUM_CLASSES, IMG_SIZE)

from torch.utils.data import WeightedRandomSampler

class_counts = train_df["class_id"].value_counts().sort_index()

class_weights_sample = 1.0 / class_counts
sample_weights = train_df["class_id"].map(class_weights_sample).values

sampler = WeightedRandomSampler(
    weights=sample_weights,
    num_samples=len(sample_weights),
    replacement=True
)

print("Sampler ready — brown spot oversampled in training batches")

"""**Dataloaders:**"""

train_dataset = SegmentationDataset(
    train_df,
    transform=train_transform,
    brown_spot_transform=brown_spot_transform,
    img_size=IMG_SIZE
)
val_dataset  = SegmentationDataset(val_df,  transform=val_transform, img_size=IMG_SIZE)
test_dataset = SegmentationDataset(df_test, transform=val_transform, img_size=IMG_SIZE)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE,
                          shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE,
                          shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE,
                          shuffle=False, num_workers=2, pin_memory=True)

print(f"Train batches : {len(train_loader)}")
print(f"Val batches   : {len(val_loader)}")
print(f"Test batches  : {len(test_loader)}")

"""**Model:**

UNet with EfficientNet-B5 encoder and SCSE decoder attention
"""

# Full model rebuild from scratch to clear any stale forward override
import torch.nn.functional as F

model = smp.Unet(
    encoder_name="timm-efficientnet-b5",
    encoder_weights="imagenet",
    in_channels=3,
    classes=NUM_CLASSES,
    activation=None,
    decoder_attention_type="scse",
).to(DEVICE)

class ASPPModule(nn.Module):
    def __init__(self, in_channels, out_channels=256):
        super().__init__()
        self.conv1x1 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
        self.conv_r6 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=6, dilation=6, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
        self.conv_r12 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=12, dilation=12, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
        self.conv_r18 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=18, dilation=18, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
        self.global_pool = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(in_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
        self.project = nn.Sequential(
            nn.Conv2d(out_channels * 5, in_channels, 1, bias=False),
            nn.BatchNorm2d(in_channels), nn.ReLU(inplace=True),
            nn.Dropout(0.1)
        )

    def forward(self, x):
        h, w = x.shape[2], x.shape[3]
        f1 = self.conv1x1(x)
        f2 = self.conv_r6(x)
        f3 = self.conv_r12(x)
        f4 = self.conv_r18(x)
        f5 = F.interpolate(self.global_pool(x), size=(h, w),
                           mode="bilinear", align_corners=False)
        return self.project(torch.cat([f1, f2, f3, f4, f5], dim=1))


bottleneck_ch = model.encoder.out_channels[-1]
aspp          = ASPPModule(in_channels=bottleneck_ch, out_channels=256).to(DEVICE)

# Verify decoder signature before patching
import inspect
sig = inspect.signature(model.decoder.forward)
print(f"Decoder forward signature: {sig}")

def forward_with_aspp(x):
    features     = model.encoder(x)
    features[-1] = aspp(features[-1])
    decoder_out  = model.decoder(features)   # list, not unpacked
    return model.segmentation_head(decoder_out)

model.forward = forward_with_aspp

# Sanity check with a dummy forward pass before training
model.eval()
with torch.no_grad():
    dummy  = torch.randn(2, 3, 512, 512).to(DEVICE)
    out    = model(dummy)
    print(f"Forward pass OK — output shape: {out.shape}")   # expect (2, 4, 512, 512)
model.train()

total_params = (sum(p.numel() for p in model.parameters())
              + sum(p.numel() for p in aspp.parameters()))
print(f"Total params : {total_params:,}")
print(f"Bottleneck ch: {bottleneck_ch}")
print("UNet + ASPP bottleneck ready")

"""**Loss Functions:**"""

import torch.nn.functional as F

tversky_loss = smp.losses.TverskyLoss(
    mode="multiclass",
    from_logits=True,
    alpha=0.3,
    beta=0.7,
    smooth=1e-6,
)

lovasz_loss = smp.losses.LovaszLoss(
    mode="multiclass",
    from_logits=True,
)

focal_loss = smp.losses.FocalLoss(
    mode="multiclass",
    gamma=2.0,
    normalized=True,
)

ce_loss = nn.CrossEntropyLoss(weight=class_weights)

iou_loss = smp.losses.JaccardLoss(
    mode="multiclass",
    from_logits=True,
    smooth=1e-6,
)

def boundary_loss_fn(pred, target, num_classes=4):
    loss      = 0.0
    pred_soft = torch.softmax(pred, dim=1)
    for c in range(1, num_classes):
        tgt      = (target == c).float().unsqueeze(1)
        dilated  = F.max_pool2d(tgt,  kernel_size=3, stride=1, padding=1) > 0.5
        eroded   = -F.max_pool2d(-tgt, kernel_size=3, stride=1, padding=1) > 0.5
        boundary = (dilated & ~eroded).float()
        error    = torch.abs(pred_soft[:, c:c+1] - tgt)
        loss    += (error * boundary).mean()
    return loss / (num_classes - 1)

def combined_loss(pred, target):
    base = (
        0.20 * tversky_loss(pred, target)
        + 0.25 * focal_loss(pred, target)
        + 0.25 * lovasz_loss(pred, target)
        + 0.20 * iou_loss(pred, target)
        + 0.10 * boundary_loss_fn(pred, target)
    )
    # Brown Spot FN penalty — uses raw logit for class 2 directly.
    # ← FIXED: was F.binary_cross_entropy(softmax_prob, ...) which is unsafe
    #   inside torch.amp.autocast — autocast can produce float16 tensors and
    #   BCE requires float32, causing a RuntimeError.
    #   F.binary_cross_entropy_with_logits operates on the raw logit instead,
    #   which is both autocast-safe and numerically more stable (no softmax
    #   followed by log — the two operations are fused internally).
    bs_logit      = pred[:, 2]                    # (B, H, W) raw logit, no softmax
    bs_tgt        = (target == 2).float()         # (B, H, W) binary ground truth
    bs_fn_penalty = F.binary_cross_entropy_with_logits(
        bs_logit, bs_tgt, reduction='mean'
    )
    return base + 0.10 * bs_fn_penalty

print("Loss: 0.20*Tversky(α=0.3,β=0.7) + 0.25*Focal + 0.25*Lovász + 0.20*IoU + 0.10*Boundary + 0.10*BS_FN")

"""**Metrics and TTA:**"""

import torch.nn.functional as F

def compute_dice_iou(all_preds, all_targets, num_classes=4):
    dice_scores = []
    iou_scores  = []

    for cls in range(1, num_classes):
        pred_c = (all_preds   == cls)
        tgt_c  = (all_targets == cls)

        if tgt_c.sum() == 0:
            continue

        inter = (pred_c & tgt_c).sum().item()
        union = pred_c.sum().item() + tgt_c.sum().item()

        dice_scores.append((2 * inter) / (union + 1e-7))
        iou_scores.append(inter / (union - inter + 1e-7))

    return (
        np.mean(dice_scores) if dice_scores else 0.0,
        np.mean(iou_scores)  if iou_scores  else 0.0
    )


def per_class_metrics(all_preds, all_targets, num_classes=4):
    results = {}
    for cls in range(1, num_classes):
        pred_c = (all_preds   == cls)
        tgt_c  = (all_targets == cls)

        if tgt_c.sum() == 0:
            results[cls] = (0.0, 0.0)
            continue

        inter = (pred_c & tgt_c).sum().item()
        union = pred_c.sum().item() + tgt_c.sum().item()

        results[cls] = (
            (2 * inter) / (union + 1e-7),
            inter / (union - inter + 1e-7)
        )
    return results


@torch.no_grad()
def tta_predict(model, images):
    """
    Fast 4-pass TTA used during training validation.
    Kept lightweight so validation does not slow down the training loop.
    """
    pred_orig = torch.softmax(model(images), dim=1)
    pred_hf   = torch.softmax(model(torch.flip(images, [-1])), dim=1).flip(-1)
    pred_vf   = torch.softmax(model(torch.flip(images, [-2])), dim=1).flip(-2)
    pred_r90  = torch.softmax(
        model(torch.rot90(images, 1, [-2, -1])), dim=1
    )
    pred_r90  = torch.rot90(pred_r90, -1, [-2, -1])
    return (pred_orig + pred_hf + pred_vf + pred_r90) / 4.0


@torch.no_grad()
def tta_predict_multiscale(model, images):
    """
    12-pass multi-scale TTA used only at final test evaluation.
    Runs 4 geometric augmentations (orig, hflip, vflip, rot90) at 3 scales
    (448, 512, 576) then averages all probability maps back at the native
    512×512 resolution.

    Brown Spot benefits most from this: the model sees lesions at a slightly
    larger relative scale (448 input → lesion appears larger) and smaller
    relative scale (576 → more spatial context), which smooths out the
    confidence map over lesion borders.
    """
    H, W   = images.shape[2], images.shape[3]
    scales = [448, 512, 576]
    preds  = []

    for s in scales:
        imgs_s = F.interpolate(
            images, size=(s, s), mode='bilinear', align_corners=False
        )

        # Original
        p = torch.softmax(model(imgs_s), dim=1)
        preds.append(F.interpolate(p, size=(H, W), mode='bilinear', align_corners=False))

        # Horizontal flip
        p = torch.softmax(model(torch.flip(imgs_s, [-1])), dim=1).flip(-1)
        preds.append(F.interpolate(p, size=(H, W), mode='bilinear', align_corners=False))

        # Vertical flip
        p = torch.softmax(model(torch.flip(imgs_s, [-2])), dim=1).flip(-2)
        preds.append(F.interpolate(p, size=(H, W), mode='bilinear', align_corners=False))

        # 90-degree rotation
        p     = torch.softmax(model(torch.rot90(imgs_s, 1, [-2, -1])), dim=1)
        p     = torch.rot90(p, -1, [-2, -1])
        preds.append(F.interpolate(p, size=(H, W), mode='bilinear', align_corners=False))

    return sum(preds) / len(preds)   # mean over all 12 passes


print("Metrics and TTA ready")
print("  tta_predict            : 4-pass  (validation during training)")
print("  tta_predict_multiscale : 12-pass (final test evaluation only)")

"""**Optimizer and Scheduler:**"""

optimizer = torch.optim.AdamW(
    [
        {"params": model.encoder.parameters(),           "lr": LR * 0.1},
        {"params": model.decoder.parameters(),           "lr": LR},
        {"params": model.segmentation_head.parameters(), "lr": LR},
        {"params": aspp.parameters(),                    "lr": LR},
    ],
    weight_decay=1e-4
)

MIN_LR_RATIO = 1e-3

def cosine_with_warmup(epoch):
    if epoch < WARMUP_EPOCHS:
        return (epoch + 1) / WARMUP_EPOCHS
    progress = (epoch - WARMUP_EPOCHS) / max(1, EPOCHS - WARMUP_EPOCHS)
    cosine   = 0.5 * (1.0 + math.cos(math.pi * progress))
    return max(cosine * (1.0 - MIN_LR_RATIO) + MIN_LR_RATIO, MIN_LR_RATIO)

scheduler = torch.optim.lr_scheduler.LambdaLR(
    optimizer, lr_lambda=cosine_with_warmup
)

scaler = torch.cuda.amp.GradScaler()

print(f"Optimizer  : AdamW (differential LR)")
print(f"  encoder  : {LR * 0.1:.2e}")
print(f"  decoder  : {LR:.2e}")
print(f"  seg head : {LR:.2e}")
print(f"  aspp     : {LR:.2e}")
print(f"Scheduler  : Warmup ({WARMUP_EPOCHS} ep) → CosineAnnealing over {EPOCHS} ep")
# Epoch 1 decoder LR should print as 2.00e-05 (1/10 of warmup ramp)
print(f"Expected LR at epoch 1: {LR * (1/WARMUP_EPOCHS):.2e}")

"""**Training Loop:**"""

from torch.optim.swa_utils import AveragedModel, update_bn

swa_model = AveragedModel(model)

best_dice        = 0.0
best_iou         = 0.0
best_score       = 0.0   # combined score used for saving
patience_counter = 0
SAVE_PATH = os.path.join(MODELS_DIR, "best_unet_b5_scse_v10.pth")
SWA_PATH  = os.path.join(MODELS_DIR, "swa_unet_b5_scse_v10.pth")

history = {
    "train_loss": [],
    "val_dice":   [],
    "val_iou":    [],
    "lr_decoder": []
}

ASPP_UNFREEZE_EPOCH = 10

for p in aspp.parameters():
    p.requires_grad = False
print("ASPP frozen for first 10 epochs")

for epoch in range(EPOCHS):

    # ✅ FIXED: reset ASPP LR to initial value when unfreezing
    if epoch == ASPP_UNFREEZE_EPOCH:
        for p in aspp.parameters():
            p.requires_grad = True
        optimizer.param_groups[3]["lr"] = LR
        print(f"\nASPP unfrozen at epoch {epoch+1}, LR reset to {LR:.2e}")

    model.train()
    aspp.train()
    train_losses = []
    optimizer.zero_grad(set_to_none=True)

    for step, (images, masks) in enumerate(
            tqdm(train_loader, desc=f"Train {epoch+1}/{EPOCHS}")):

        images = images.to(DEVICE)
        masks  = masks.to(DEVICE)

        with torch.amp.autocast('cuda'):
            outputs     = model(images)
            loss        = combined_loss(outputs, masks)
            loss_scaled = loss / ACCUM_STEPS

        scaler.scale(loss_scaled).backward()
        train_losses.append(loss.item())

        should_step = (
            (step + 1) % ACCUM_STEPS == 0
            or (step + 1) == len(train_loader)
        )
        if should_step:
            scaler.unscale_(optimizer)
            # ✅ FIXED: clip ASPP gradients too
            all_params = list(model.parameters()) + list(aspp.parameters())
            torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)

    current_lr = optimizer.param_groups[1]["lr"]
    scheduler.step()

    if epoch >= SWA_START:
        swa_model.update_parameters(model)

    use_tta_val = (epoch >= TTA_VAL_START)
    model.eval()
    aspp.eval()
    all_preds   = []
    all_targets = []

    with torch.no_grad():
        for images, masks in val_loader:
            images = images.to(DEVICE)
            masks  = masks.to(DEVICE)
            if use_tta_val:
                probs = tta_predict(model, images)
                preds = torch.argmax(probs, dim=1).cpu()
            else:
                preds = torch.argmax(model(images), dim=1).cpu()
            all_preds.append(preds)
            all_targets.append(masks.cpu())

    all_preds   = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)

    train_loss        = np.mean(train_losses)
    val_dice, val_iou = compute_dice_iou(all_preds, all_targets, NUM_CLASSES)

    history["train_loss"].append(train_loss)
    history["val_dice"].append(val_dice)
    history["val_iou"].append(val_iou)
    history["lr_decoder"].append(current_lr)

    frozen_tag = "[ASPP frozen]" if epoch < ASPP_UNFREEZE_EPOCH else "[ASPP active]"
    tta_tag    = "[TTA]" if use_tta_val else "[single]"
    print(f"\nEpoch {epoch+1}/{EPOCHS}  |  LR (decoder): {current_lr:.2e}  |  {tta_tag}  {frozen_tag}")
    print(f"  Train Loss : {train_loss:.4f}")
    print(f"  Val Dice   : {val_dice:.4f}")
    print(f"  Val IoU    : {val_iou:.4f}")

    # ✅ FIXED: save on combined score weighted toward IoU (the actual target metric)
    score = 0.4 * val_dice + 0.6 * val_iou
    if score > best_score:
        best_score       = score
        best_dice        = val_dice
        best_iou         = val_iou
        patience_counter = 0
        torch.save(
            {
                "epoch":                epoch + 1,
                "model_state_dict":     model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "aspp_state_dict":      aspp.state_dict(),
                "best_dice":            float(best_dice),
                "best_iou":             float(best_iou),
                "best_score":           float(best_score),
                "tta_val_start":        TTA_VAL_START,
                "mask_threshold":       MASK_THRESHOLD,
            },
            SAVE_PATH
        )
        print(f"  ✅ Saved best model (Dice: {best_dice:.4f}  IoU: {best_iou:.4f}  Score: {best_score:.4f})")
    else:
        patience_counter += 1
        print(f"  No improvement ({patience_counter}/{PATIENCE})  "
              f"[best score: {best_score:.4f}  Dice: {best_dice:.4f}  IoU: {best_iou:.4f}]")
        if patience_counter >= PATIENCE:
            print(f"\nEarly stopping at epoch {epoch+1}")
            break

print("\nUpdating SWA BatchNorm statistics...")
update_bn(train_loader, swa_model, device=DEVICE)
torch.save({
    "model_state_dict": swa_model.module.state_dict(),
    "best_dice":        float(best_dice),
    "best_iou":         float(best_iou),
    "mask_threshold":   MASK_THRESHOLD,
}, SWA_PATH)
print(f"SWA model saved to {SWA_PATH}")
print(f"\nTraining complete  |  Best Val Dice: {best_dice:.4f}  IoU: {best_iou:.4f}")

"""**Training Curves:**"""

epochs_ran = len(history["train_loss"])
x_axis     = range(1, epochs_ran + 1)

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.suptitle("Training History — UNet B5 SCSE", fontsize=14)

axes[0].plot(x_axis, history["train_loss"], color="steelblue")
axes[0].set_title("Train Loss")
axes[0].set_xlabel("Epoch")
axes[0].grid(True)

axes[1].plot(x_axis, history["val_dice"],  color="darkorange", label="Dice")
axes[1].plot(x_axis, history["val_iou"],   color="purple",     label="IoU")
axes[1].axhline(y=0.80, color="red",   linestyle="--", alpha=0.5, label="Target Dice 0.80")
axes[1].axhline(y=0.70, color="green", linestyle="--", alpha=0.5, label="Target IoU 0.70")
axes[1].axhline(y=best_dice, color="gray", linestyle=":",
                label=f"Best Dice: {best_dice:.4f}")
axes[1].set_title("Val Metrics")
axes[1].set_xlabel("Epoch")
axes[1].legend(fontsize=8)
axes[1].grid(True)

axes[2].plot(x_axis, history["lr_decoder"], color="green")
axes[2].set_title("Learning Rate (decoder)")
axes[2].set_xlabel("Epoch")
axes[2].set_yscale("log")
axes[2].grid(True)

plt.tight_layout()
plt.savefig(os.path.join(META_DIR, "segmentation_final_training_curves_v9.png"), dpi=120)
plt.show()
print("Saved segmentation_final_training_curves_v9.png")

"""**Final Test Evaluation with TTA:**"""

# ── install pydensecrf is no longer needed — CRF removed ─────────────────────
# CRF with sxy=80 bilateral radius is larger than most Brown Spot lesions;
# it smoothed BS predictions into background, dropping BS IoU by 0.097.
# Removed entirely. If you want to revisit CRF, use sxy=5–10 and compat=3.

# ── rebuild model and ASPP ────────────────────────────────────────────────────
model = smp.Unet(
    encoder_name="timm-efficientnet-b5",
    encoder_weights=None,
    in_channels=3,
    classes=NUM_CLASSES,
    activation=None,
    decoder_attention_type="scse",
).to(DEVICE)

bottleneck_ch = model.encoder.out_channels[-1]
aspp          = ASPPModule(in_channels=bottleneck_ch, out_channels=256).to(DEVICE)

def forward_with_aspp(x):
    features     = model.encoder(x)
    features[-1] = aspp(features[-1])
    decoder_out  = model.decoder(features)
    return model.segmentation_head(decoder_out)

model.forward = forward_with_aspp

checkpoint = torch.load(SAVE_PATH, map_location=DEVICE, weights_only=False)
model.load_state_dict(checkpoint["model_state_dict"])
aspp.load_state_dict(checkpoint["aspp_state_dict"])

ckpt_dice = checkpoint.get("best_dice", 0.0)
ckpt_iou  = checkpoint.get("best_iou",  "n/a")
print(f"Loaded checkpoint from epoch {checkpoint['epoch']} "
      f"(Val Dice: {ckpt_dice:.4f}  Val IoU: {ckpt_iou})")

model.eval()
aspp.eval()

# ── Multi-scale TTA inference ─────────────────────────────────────────────────
all_probs_tta   = []
all_targets_tta = []

print("Running multi-scale TTA inference (12 passes per image)...")
with torch.no_grad():
    for images, masks in tqdm(test_loader, desc="Testing (multi-scale TTA)"):
        images = images.to(DEVICE)
        masks  = masks.to(DEVICE)
        probs  = tta_predict_multiscale(model, images)
        all_probs_tta.append(probs.cpu())
        all_targets_tta.append(masks.cpu())

all_probs_tta   = torch.cat(all_probs_tta)   # (N, 4, H, W)
all_targets_tta = torch.cat(all_targets_tta) # (N, H, W)

# ── Baseline: raw argmax ──────────────────────────────────────────────────────
all_preds_baseline          = torch.argmax(all_probs_tta, dim=1)
baseline_dice, baseline_iou = compute_dice_iou(all_preds_baseline, all_targets_tta, NUM_CLASSES)
per_cls_baseline            = per_class_metrics(all_preds_baseline, all_targets_tta, NUM_CLASSES)

print("\n" + "="*55)
print("BASELINE TEST RESULTS  (multi-scale TTA argmax)")
print("="*55)
print(f"  Mean Dice : {baseline_dice:.4f}  {'✅' if baseline_dice >= 0.80 else '❌'}")
print(f"  Mean IoU  : {baseline_iou:.4f}  {'✅' if baseline_iou  >= 0.70 else '❌'}")
print("\nPer-Class:")
for cls_id, (dice, iou) in per_cls_baseline.items():
    name = CLASS_NAMES.get(cls_id, f"class_{cls_id}")
    print(f"  [{cls_id}] {name:25s}  Dice={dice:.4f}  IoU={iou:.4f}")

# ── Connected component filter ────────────────────────────────────────────────
from skimage import measure

def filter_small_components(pred_tensor, thresholds=None):
    if thresholds is None:
        thresholds = {1: 200, 2: 30, 3: 150}
    result = pred_tensor.clone()
    for i in range(len(pred_tensor)):
        arr = result[i].numpy().copy()
        for class_id, min_px in thresholds.items():
            cls_mask = (arr == class_id)
            if cls_mask.sum() == 0:
                continue
            labeled = measure.label(cls_mask)
            for region in measure.regionprops(labeled):
                if region.area < min_px:
                    arr[labeled == region.label] = 0
        result[i] = torch.from_numpy(arr)
    return result

# ── 2D grid sweep: CC threshold × confidence threshold ───────────────────────
# Previous runs swept these independently, which misses the interaction.
# Here we sweep all combinations and find the true joint optimum.
#
# CC filter removes small spurious components (reduces FP noise).
# Confidence threshold zeros low-confidence BS predictions (reduces FP blobs).
# Applying CC first, then threshold, is the correct order:
#   1) remove tiny isolated predictions
#   2) then zero the remaining low-confidence ones
print("\n" + "="*70)
print("2D GRID SWEEP: CC min_pixels (BS) × Confidence Threshold (BS)")
print("="*70)

cc_thresholds   = [0, 15, 30, 50, 80]
conf_thresholds = [0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75]

# Print header
header = f"{'cc\\conf':>10}" + "".join(f"  {t:.2f}" for t in conf_thresholds)
print(header)
print("-" * len(header))

best_grid_iou    = baseline_iou
best_grid_preds  = all_preds_baseline.clone()
best_cc          = 0
best_conf        = None

for cc_t in cc_thresholds:
    row_str = f"{cc_t:>10}"
    for conf_t in conf_thresholds:
        # Step 1: Apply CC filter
        thresholds = {1: 200, 2: cc_t, 3: 150}
        preds_step1 = filter_small_components(
            all_preds_baseline.clone(), thresholds=thresholds
        )
        # Step 2: Zero low-confidence BS predictions
        bs_prob     = all_probs_tta[:, 2]
        low_conf    = (preds_step1 == 2) & (bs_prob < conf_t)
        preds_step1[low_conf] = 0

        _, iou = compute_dice_iou(preds_step1, all_targets_tta, NUM_CLASSES)
        marker = "*" if iou > best_grid_iou else " "
        row_str += f"  {iou:.4f}{marker}"

        if iou > best_grid_iou:
            best_grid_iou   = iou
            best_grid_preds = preds_step1.clone()
            best_cc         = cc_t
            best_conf       = conf_t

    print(row_str)

if best_conf is not None:
    print(f"\n✅ Best combination: CC min_px={best_cc}  Conf={best_conf:.2f}  IoU={best_grid_iou:.4f}")
    final_preds = best_grid_preds
else:
    print(f"\nNo combination beat baseline — using raw argmax")
    final_preds = all_preds_baseline

final_dice_val, final_iou_val = compute_dice_iou(final_preds, all_targets_tta, NUM_CLASSES)
final_per_cls = per_class_metrics(final_preds, all_targets_tta, NUM_CLASSES)
final_desc    = f"MS-TTA + CC({best_cc}px) + BSthresh({best_conf})"

# ── Final summary ─────────────────────────────────────────────────────────────
print("\n" + "="*55)
print(f"FINAL TEST RESULTS  ({final_desc})")
print("="*55)
print(f"  Mean Dice : {final_dice_val:.4f}  {'✅ TARGET MET' if final_dice_val >= 0.80 else '❌ below 0.80'}")
print(f"  Mean IoU  : {final_iou_val:.4f}  {'✅ TARGET MET' if final_iou_val  >= 0.70 else '❌ below 0.70'}")
print("\nPer-Class:")
for cls_id, (dice, iou) in final_per_cls.items():
    name = CLASS_NAMES.get(cls_id, f"class_{cls_id}")
    print(f"  [{cls_id}] {name:25s}  Dice={dice:.4f}  IoU={iou:.4f}")

"""**Save Results:**"""

results = {
    "Model":        "UNet (timm-efficientnet-b5, SCSE, ImageNet) v10 + ASPP",
    "Mean Dice":    round(final_dice_val, 4),
    "Mean IoU":     round(final_iou_val,  4),
    "TTA":          "HFlip + VFlip + Rot90",
    "BS Threshold": sweep_best_thresh,
    "Mask Threshold": MASK_THRESHOLD,
}
for cls_id, (dice, iou) in final_per_cls.items():
    name = CLASS_NAMES.get(cls_id, f"class_{cls_id}")
    results[f"{name} Dice"] = round(dice, 4)
    results[f"{name} IoU"]  = round(iou,  4)

results_path = os.path.join(META_DIR, "segmentation_results_v10.csv")
pd.DataFrame([results]).to_csv(results_path, index=False)

print("Final Results:")
print(pd.DataFrame([results]).T.to_string(header=False))
print(f"\nSaved to {results_path}")